#!/usr/bin/env bash
if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
# Script to setup devonfw-ide environment. Will actually be sourced,
# hash bang only for filetype detection and editor syntax support

# shellcheck source=scripts/functions-core
source "${DEVON_IDE_HOME}/scripts/functions-core"
doEnvironmentProject "${@}"
