#!/bin/bash
# Script to setup devon-ide environment. Will actually be sourced,
# hash bang only for filetype detection and editor syntax support

if [ -n "${SOFTWARE_PATH}" ]
then
  # "remove" previous IDE from $PATH
  export PATH=`echo $PATH | sed "s~${SOFTWARE_PATH}[^:]*::*~~g"`
fi
export DEVON_IDE_HOME=${PWD}

# load and setup configuration
source "${DEVON_IDE_HOME}/scripts/variables"
if [ -f "${DEVON_IDE_HOME}/conf/variables" ]
then
  source "${DEVON_IDE_HOME}/conf/variables"
fi
if [ -f "${SETTINGS_PATH}/ide-properties" ]
then
  source "${SETTINGS_PATH}/ide-properties"
fi
if [ -z "${WORKSPACE}" ]
then
  export WORKSPACE=main
fi
export WORKSPACE_PATH=${DEVON_IDE_HOME}/workspaces/${WORKSPACE}
SOFTWARE_PATH=${DEVON_IDE_HOME}/software

if [ ! -d "${SETTINGS_PATH}" ]
then
  ${DEVON_IDE_HOME}/scripts/command/update settings
  result=${?}
  if [ ${result} != 0 ]
  then
    echo "Failed to install settings with exit code ${result}"
    echo "Please try to manually setup your settings."
  fi
fi
# copy defaults
if [ ! -d "${DEVON_IDE_HOME}/conf" ]
then
  mkdir "${DEVON_IDE_HOME}/conf"
fi
if [ -d "${SETTINGS_PATH}" ]
then
  if [ ! -e "${DEVON_IDE_HOME}/conf/variables" ]
  then
    cp "${SETTINGS_PATH}/devon/variables" "${DEVON_IDE_HOME}/conf/"
  fi
  if [ ! -e "${DEVON_IDE_HOME}/conf/variables-customized" ]
  then
    cp "${SETTINGS_PATH}/devon/variables-customized" "${DEVON_IDE_HOME}/conf/"
  fi
fi

# Setup path
if [ ! -d "${SOFTWARE_PATH}" ]
then
  echo "*** ATTENTION ***"
  echo "Your devon-ide is missing the software at ${SOFTWARE_PATH}"
  ${DEVON_IDE_HOME}/scripts/command/install
  result=${?}
  if [ ${result} != 0 ]
  then
    echo "Failed to install software with exit code ${result}"
    echo "Please try to manually setup your software."
    return -1
  fi
fi
for SOFTWARE_FOLDER in ${SOFTWARE_PATH}/*
do
  if [ -d "${SOFTWARE_FOLDER}/bin" ]
  then
    PATH="${SOFTWARE_FOLDER}/bin:${PATH}"
  else
    PATH="${SOFTWARE_FOLDER}:${PATH}"
  fi
  # Load custom configuration of software
  if [ -e "${SOFTWARE_FOLDER}/ide-config" ]
  then
    source "${SOFTWARE_FOLDER}/ide-config"
  fi
done

# Modularization: run all linux/mac/bsd scripts from scripts/init/
# To customize devon-ide you may add your own scripts in this folder
for SCRIPT in ${DEVON_IDE_HOME}/scripts/init/*
do
  if [ "${SCRIPT##*.}" != "bat" ]
  then
    source ${SCRIPT}
  fi
done

# load user settings late so variables like M2_REPO can be overriden
if [ -f "${DEVON_IDE_HOME}/conf/variables-customized" ]
then
  source "${DEVON_IDE_HOME}/conf/variables-customized"
fi

export PATH

echo "IDE environment has been initialized."
