#!/usr/bin/env bash
if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
# Script to setup devonfw-ide environment. Will actually be sourced,
# hash bang only for filetype detection and editor syntax support

# shellcheck source=scripts/functions-core
source "${DEVON_IDE_HOME}/scripts/functions-core"

if [ ! -f "${DEVON_IDE_HOME}/.devon.software.version" ] && [ -d "${DEVON_IDE_HOME}/workspaces" ] && [ -d "${DEVON_IDE_HOME}/software" ]
then
  doRunCommand "'$DEVON_IDE_HOME/scripts/migration'"
fi

doEnvironmentProject "${@}"
