#!/usr/bin/env bash

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/functions

doEcho "\nRun migration scripts to version ${1}."
migrations="$(dirname "${0}")/migrations/*"
for migration in $(ls ${migrations} | sort -n)
do
  from_version="${1}"
  to_version="${migration/*\//}"
  doVersionCompare "${from_version}" "${to_version}"
  result="${?}"
  if [ "${result}" -eq 0 ] || [ "${result}" -eq 2 ]
  then
    "${migration}"
  fi	
done
