#!/usr/bin/env bash

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/functions

from_version=2023.01.001
devon_version="${DEVON_IDE_HOME}/.devon.software.version"

if [ -f "${devon_version}" ]  
then
  from_version="$(cat ${devon_version})"
fi

MIGRATIONS_DIR="${DEVON_IDE_HOME}/scripts/migrations"

if [ -d "${MIGRATIONS_DIR}" ]
then
  cd "${MIGRATIONS_DIR}"
  for migrate_to_version in  $(ls | sort -n)
  do
    doVersionCompare "${from_version}" "${migrate_to_version}"
    result="${?}"
    if [ "${result}" -eq 2 ]
    then
      doEcho "Run migration to version ${migrate_to_version}"
      bash "${migrate_to_version}"
      migration_result="${?}"
      if [ "${migration_result}" -ne 0 ]
      then
        doAskToContinue "The migration to version ${migrate_to_version} failed. Would you like to continue?"
      else
        echo "${migrate_to_version}" > "${devon_version}"
        doEcho "${devon_version} is set to version ${migrate_to_version}"
      fi
    fi
  done
else
  doWarning "Migrations directory does not exist in ${MIGRATIONS_DIR}"
fi