#!/usr/bin/env bash
kubernetes_check=$(kubectl version --client 2>/dev/null)
source "$(dirname "${0}")"/functions
if  [[ ! $kubernetes_check == *"Client Version"* ]]; then
	doEcho "Hint:You may be required to enter sudo user password of your Windows Subsystem for Linux(WSL) when prompted during the setup."
	doEcho Installing Kubectl and K3D...
	curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
	sudo mv ./kubectl /usr/local/bin/kubectl
	wget -q -O - https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
	sudo chmod 755 /usr/local/bin/kubectl /usr/local/bin/k3d	
	
	if doIsDockerInstalledOnWSL
	then
		k3d cluster create devonfw-cluster
		export KUBECONFIG=$(k3d kubeconfig get devonfw-cluster)
	else
		doEcho "Please install docker using devon docker setup to be able to create clusters using k3d."
	fi

	doEcho Kubernetes is installed successfully on your WSL.
else 
	doEcho Kubernetes already installed on your WSL Distribution and available for use. devonfw-ide did not make any changes. 
fi
