#!/usr/bin/env bash
docker_check=$(docker --version)
if [[ $docker_check != *"Docker version"* ]];then
	echo "Installing Docker on WSL..."
	sudo apt-get update -y
	sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common gnupg-agent
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
	sudo apt-get update -y
	sudo apt-get install -y docker-ce docker-ce-cli containerd.io
	sudo service docker start
	sudo usermod -aG docker $USER
	echo Docker installed successfully.
else 
    echo Docker already installed on WSL.
fi 
docker version