#!/bin/bash
#cd `dirname $0`

export WORKSPACE=$MAIN_BRANCH
export MODE="-i"

if [ "$1" == "--new" ]; then
	export MODE="-x"
  if [ -n "$2" ]; then
		export WORKSPACE=$2
  fi
else if [ -n "$1" ]
	export WORKSPACE=$1
fi

. scripts/environment-project
   
java -jar $SCRIPTS_PATH/$IDE_CONFIGURATOR -t "$SETTINGS_PATH\eclipse\workspace" -w "$WORKSPACE_PATH" -v "$REPLACEMENT_PATTERNS_PATH" $MODE





