#!/bin/bash

source "$(dirname "${0}")"/functions-test

success=0
failure=0
total=0

function doTests() {
for testpath in "$(dirname $0)"/"${1}"-*
do
  testcase="${testpath/*\//}"
  echo "Running test #${total}: ${testcase}"
  mkdir -p "${testcase}/conf"
  cd "${testcase}"
  echo "export M2_REPO=~/.m2/repository" > "conf/devon.properties"
  "${testpath}" &> errorLog
  result=${?}
  if [ "${result}" == 0 ]
  then
    doSuccess "[SUCCESS] Succeeded running test #${total}: ${testcase}"
    let "success++"
  else
    doError "[ERROR] Failed running test #${total}: ${testcase} - exit code ${result}"
    let "failure++"
    doError "[ERROR LOG] ${testcase}" >> ../errorLogs
    echo -e "$(cat errorLog)\n" >> ../errorLogs
    echo -e "\n[ERROR] Failed running test #${total}: ${testcase} - exit code ${result}" >> ../logList
  fi
  let "total++"
  cd ..
done
}

mkdir -p ~/.devon
touch ~/.devon/.license.agreement
rm -rf integration-test
mkdir -p integration-test
cd integration-test
export DEVON_SKIP_PROJECT_SETUP=true
doTests "test"
[[ "${INTEGRATION_TEST}" == true ]] && doTests "integration-test"
echo -e "\n*****************************************************"
echo "Executed #${total} test(s), #${success} succeeded and #${failure} failed"
echo -e "*****************************************************\n"
if [ "${failure}" == 0 ]
then
  doSuccess "All test succeeded. Fine!"
else
  doWarning "There are test failures! Please check the logs and fix errors.\n"
  cat errorLogs
  cat logList
  exit 1
fi