#!/bin/bash

function doCommandTest()  {
  CLI="${PWD}/scripts/devon"
  "${CLI}" "${1}" --batch setup
  exit "${?}"
}

function doExtract() {
  if [ -f "${1}" ]
  then
    tar xfz "${1}" || exit 1
  else
    echo "Could not find and extract release ${1}"
    exit 1
  fi
}

# $@: success message
function doSuccess() {
  echo -e "\033[92m${*}\033[39m"
}

# $@: warning message
function doWarning() {
  echo -e "\033[93m${*}\033[39m"
}

# $@: messages to output
function doError() {
  echo -e "\033[91m${1}\033[39m"
}

function doIsMacOs() {
  if [ "${OSTYPE:0:6}" = "darwin" ]
  then
    return
  fi
  return 255
}

function doIsWindows() {
  if [ "${OSTYPE}" = "cygwin" ] || [ "${OSTYPE}" = "msys" ]
  then
    return
  fi
  return 255
}
