#!/bin/bash

source "$(dirname "${0}")"/functions-test
if doIsWindows
then
  doCommandTest pip
else
  echo "The integration-test for pip is currently disabled for MacOS and Linux systems"
  exit 0
fi
