#!/bin/bash

source "$(dirname "${0}")"/functions-test

CLI="${PWD}/scripts/devon"
REPO_URL="https://repo1.maven.org/maven2/com/palantir/launching"
MAC_PATH=$(doIsMacOs && echo "service/" || echo "")
TOOL_A="go-init"
TOOL_VERSION_A="1.22.0"
TOOL_PATH_A="${PWD}/software/${TOOL_A}/${MAC_PATH}bin/darwin-amd64/${TOOL_A}"
TOOL_B="go-java-launcher"
TOOL_VERSION_B="1.34.0"
TOOL_PATH_B="${PWD}/software/${TOOL_B}/${MAC_PATH}bin/darwin-amd64/${TOOL_B}"
CUSTOM_TOOLS="DEVON_IDE_CUSTOM_TOOLS=(${TOOL_A}:${TOOL_VERSION_A}:all:${REPO_URL} ${TOOL_B}:${TOOL_VERSION_B}:all:)"

echo -e "\n${CUSTOM_TOOLS}" >> "${PWD}/settings/devon.properties"
"${CLI}" ide update

[[ -f "${TOOL_PATH_A}" && -f "${TOOL_PATH_B}" ]]
exit ${?}
