#!/bin/bash

CLI="${PWD}/scripts/devon"
SHARED_DIR="${PWD}/shared"
echo -e "\nDEVON_SOFTWARE_PATH=${SHARED_DIR}" >> "${PWD}/conf/devon.properties"
"${CLI}" java setup

[ -d "${SHARED_DIR}/default/java" ]
exit ${?}
