#!/bin/bash

CLI="${PWD}/scripts/devon"
JAVA_VERSION='11*'
EXTRA_VERSION=$(head -n 1 "${PWD}"/mirrors/java/available-versions)

echo -e "\nJAVA_VERSION=${JAVA_VERSION}" >> "${PWD}/conf/devon.properties"
echo -e "\nEXTRA_JAVA_VERSION=${EXTRA_VERSION}" >> "${PWD}/conf/devon.properties"
"${CLI}" java setup
JAVA_TEST=$(cat "${PWD}"/software/java/.devon.software.version)
EXTRA_TEST=$(cat "${PWD}"/software/extra/java/.devon.software.version)

if [ "${JAVA_TEST::3}" != "11." ]
then
  echo "ERROR: Expected Java 11 but found version ${JAVA_TEST}"
  exit 1
fi
if [ "${EXTRA_TEST}" != "${EXTRA_VERSION}" ]
then
  echo "ERROR: Expected Java extra version ${EXTRA_VERSION} but found version ${EXTRA_TEST}"
  exit 1
fi
