#!/bin/bash

cd ../test-setup
CLI="${PWD}/scripts/devon"
rm -fR "${PWD}/software"

SHARED_DIR="${PWD}/shared"
echo -e "\nDEVON_SOFTWARE_PATH=${SHARED_DIR}" >> "${PWD}/conf/devon.properties"
"${CLI}" java setup

rm "${PWD}/conf/devon.properties"
[ -d "${SHARED_DIR}/default/java" ]
exit ${?}
