#!/bin/bash

cd ../test-setup
CLI="${PWD}/scripts/devon"
rm -fR "${PWD}/software"

SHARED_DIR="${PWD}/shared"
echo "DEVON_SOFTWARE_PATH=${SHARED_DIR}" >> "${PWD}/conf/devon.properties"
"${CLI}" java setup
JAVA_DIR=$(which java)

if [ "${SHARED_DIR}/default/java/bin/java" = "${JAVA_DIR}" ]
then
  rm "${PWD}/conf/devon.properties"
  exit 0
else
  rm "${PWD}/conf/devon.properties"
  exit 1
fi
