#!/bin/bash

cd ../test-setup
CLI="${PWD}/scripts/devon"
EXTRA_VERSION=$(head -n 1 "${PWD}"/mirrors/java/available-versions)

echo "EXTRA_JAVA_VERSION=${EXTRA_VERSION}" >> "${PWD}/conf/devon.properties"
"${CLI}" java setup

if [ -x "${PWD}/software/extra/java/bin/java" ]
then
  rm "${PWD}/conf/devon.properties"
  exit 0
else
  rm "${PWD}/conf/devon.properties"
  exit 1
fi