#!/bin/bash

function doExtract() {
  if [ -f "${1}" ]
  then
    tar xfz "${1}" || exit 1
  else
    echo "Could not find and extract release ${1}"
    exit 1
  fi
}

doExtract ../../devon-ide-scripts-*.tar.gz
./setup "-"
exit ${?}
