#!/bin/bash

# This test checks the setup.bat and devon.bat for windows.

source "$(dirname "${0}")"/functions-test

doExtract ../../devonfw-ide-scripts-*.tar.gz
TESTS_PATH=$(dirname "${0}")
cmd "/c ${TESTS_PATH}\setup-windows.bat"