#!/bin/bash

if ! command -v shellcheck > /dev/null
then
  echo "WARNING: shellcheck is not installed on your machine."
  echo "Please install it to properly check bash scripts!"
  exit
fi
cd ../../../../scripts/src/main/resources || exit 1
OPTS="-e SC2181"
#shellcheck ${OPTS} -a devon
shellcheck -x -e SC2181 setup scripts/devon scripts/environment-project scripts/functions scripts/command/*
