#!/bin/bash

SCRIPTS_PATH="../../../../scripts/src/main/resources/scripts"
( set -o pipefail; grep "function " "${SCRIPTS_PATH}/functions" "${SCRIPTS_PATH}/functions-core" | sed 's/.*function //' | sed 's/() {//' | sort -u > functions.list ) || exit 1
( set -o pipefail; grep "=== " "../../../../documentation/functions.asciidoc"  | sed 's/=== //' | sort -u > functions.adoc.list ) || exit 1

diff functions.list functions.adoc.list
if [ "$?" = 0 ]
then
  echo "Documentation of functions and function declarations are in sync."
  echo "Awesome!"
else
  echo "Documentation of functions does not match function declarations!"
  echo "Please keep function documentation and declarations in sync!"
  exit 1
fi
