#!/bin/bash
success=0
failure=0
failures=()
total=0
cd ../test-setup
CLI="${PWD}/scripts/devon"
cd scripts/command
for command in *
do
  "${CLI}" "${command}"
  result=${?}
  if [ "${result}" == 0 ]
  then
    echo "[SUCCESS] Succeeded running command #${total}: ${command}"
    let "success++"
  else
    echo "[ERROR] Failed running command #${total}: ${command} - exit code ${result}"
    failures+=("${command}")
    let "failure++"
  fi
  let "total++"
done
echo
echo "*****************************************************"
echo "Executed #${total} commands(s), #${success} succeeded and #${failure} failed"
if [ "${failure}" == 0 ]
then
  echo "All commands succeeded. Fine!"
else
  echo "There are commands failures! Please check and fix the following commands."
  for i in "${failures[@]}"
  do
    echo "${i}"
  done
  exit 1
fi

