#!/bin/bash
set -e

cd `dirname $0`

if [ -n "$1" ]; then
    WORKSPACE=$1
fi

. scripts/environment-project
CONF_PATH=$PWD/conf

if [ ! -d "$SOFTWARE_PATH" ]; then
    echo "Could not find folder '$SOFTWARE_PATH' (from variable SOFTWARE_PATH)"
    echo "Execution aborted"
    exit 1
fi
if [ ! -d "$WORKSPACES_PATH" ]; then
    echo "Could not find folder '$WORKSPACES_PATH' (from variable WORKSPACES_PATH)"
    echo "Execution aborted"
    exit 1
fi
if [ ! -d "$WORKSPACE_PATH" ]; then
    echo "Could not find folder '$WORKSPACE_PATH' (from variable WORKSPACE_PATH)"
    echo "Execution aborted"
    exit 1
fi
if [ ! -d "$SETTINGS_PATH" ]; then
    echo "Could not find folder '$SETTINGS_PATH' (from variable SETTINGS_PATH)"
    echo "Execution aborted"
    exit 1
fi

if [ ! -e "$CONF_PATH/.m2" ]; then
    mkdir -p "$CONF_PATH/.m2"
fi
if [ ! -e "$CONF_PATH/.m2/settings.xml" ]; then
    cp "$SETTINGS_PATH/maven/settings.xml" "$CONF_PATH/.m2/settings.xml"
    echo "Copied $SETTINGS_PATH/maven/settings.xml to $CONF_PATH/.m2/settings.xml"
fi

# TODO: Port subversion config


ECLIPSE_TEMPLATES_PATH=$SETTINGS_PATH/eclipse/workspace
if [ ! -d "$ECLIPSE_TEMPLATES_PATH" ]; then
    echo "Could not find folder '$ECLIPSE_TEMPLATES_PATH' (from variable ECLIPSE_TEMPLATES_PATH)"
    echo "Execution aborted"
    exit 1
fi
if [ ! -e "$REPLACEMENT_PATTERNS_PATH" ]; then
    echo "WARNING: Could not find file '$REPLACEMENT_PATTERNS_PATH' (from variable REPLACEMENT_PATTERNS_PATH)"
    echo "Please check your ide-properties from $SETTINGS_PATH"
fi

# copys/merges the *.prefs form $SETTINGS_PATH/eclipse/workspace/... to specified Eclipse workspace
java -jar $SCRIPTS_PATH/$IDE_CONFIGURATOR -t "$ECLIPSE_TEMPLATES_PATH" -w "$WORKSPACE_PATH" -v "$REPLACEMENT_PATTERNS_PATH" -u
echo "Eclipse preferences for workspace $WORKSPACE have been created/updated"

if [ ! -e "eclipse-$WORKSPACE" ]
then
 echo "#!/bin/bash" > eclipse-$WORKSPACE 
 echo "cd \`dirname \$0\`" >> eclipse-$WORKSPACE 
 echo "export WORKSPACE=$WORKSPACE" >> eclipse-$WORKSPACE 
 echo "scripts/eclipse-start" >> eclipse-$WORKSPACE 
 chmod a+x eclipse-$WORKSPACE
fi
