#!/bin/bash

set -e
cd `dirname $0`

if [ -n $1 ]; then
    WORKSPACE=$1
fi

. scripts/environment-project

if [ ! -d $OASP_PROJECT_HOME/$OFTWARE_PATH ]; then
    echo "Could not find folder $SOFTWARE_PATH"
    echo "If you want to change its name see the variables"
    echo "Execution aborted"
    exit 1
fi
if [ ! -d $OASP_PROJECT_HOME/$WORKSPACES_PATH ]; then
    echo "Could not find folder $OASP_PROJECT_HOME/$WORKSPACES_PATH"
    echo "If you want to change its name see the variables"
    echo "Execution aborted"
    exit 1
fi
if [ ! -d $OASP_PROJECT_HOME/$WORKSPACE_PATH ]; then
    echo "Could not find workspace $OASP_PROJECT_HOME/$WORKSPACE_PATH"
    echo "Execution aborted"
    exit 1
fi
if [ ! -d $OASP_PROJECT_HOME/$SETTINGS_PATH ]; then
    echo "Could not find folder $OASP_PROJECT_HOME/$SETTINGS_PATH"
    echo "If you want to change its name see the variables"
    echo "Execution aborted"
    exit 1
fi


if [ ! -e $OASP_PROJECT_HOME/$CONF_PATH/.m2 ]; then
    mkdir -p $OASP_PROJECT_HOME/$CONF_PATH/.m2
fi
if [ ! -e $OASP_PROJECT_HOME/$CONF_PATH/.m2/settings.xml ]; then
    cp $OASP_PROJECT_HOME/$SETTINGS_PATH/maven/settings.xml $OASP_PROJECT_HOME/$CONF_PATH/.m2/settings.xml
    echo "Copied $SETTINGS_PATH/maven/settings.xml to $CONF_PATH/.m2/settings.xml"
    cp $OASP_PROJECT_HOME/$SETTINGS_PATH/version/settings.json $OASP_PROJECT_HOME/$CONF_PATH/settings.json
    echo "Copied $SETTINGS_PATH/version/settings.json to $CONF_PATH/settings.json"
fi

# TODO: Port subversion config


if [ ! -d $ECLIPSE_TEMPLATES_PATH ]; then
    echo "Could not find folder $ECLIPSE_TEMPLATES_PATH"
    echo "Execution aborted"
    exit 1
fi
if [ ! -e $ECLIPSE_REPLACEMENT_PATTERNS_PATH ]; then
    echo "Could not find file $ECLIPSE_REPLACEMENT_PATTERNS_PATH"
    echo "Execution aborted"
    exit 1
fi

# copys/merges the *.prefs form $SETTINGS_PATH/eclipse/workspace/... to specified Eclipse workspace
# In order to run this jar requires the following environment variables:
# WORKSPACE_PATH, ECLIPSE_TEMPLATES_PATH and REPLACEMENT_PATTERNS_PATH
#echo $WORKSPACE_REL_PATH
#echo $ECLIPSE_TEMPLATES_REL_PATH
#WORKSPACE_PATH=$WORKSPACE_REL_PATH
REPLACEMENT_PATTERNS_PATH=$ECLIPSE_REPLACEMENT_PATTERNS_PATH

java -jar $SCRIPTS_PATH/$ECLIPSE_CONFIGURATOR -u
echo "Eclipse preferences for workspace $WORKSPACE have been created/updated"

if [ ! -e "eclipse-$WORKSPACE" ]
then
 echo "#!/bin/bash" > eclipse-$WORKSPACE 
 echo "cd \`dirname \$0\`" >> eclipse-$WORKSPACE 
 echo "export WORKSPACE=$WORKSPACE" >> eclipse-$WORKSPACE 
 echo "scripts/eclipse-start" >> eclipse-$WORKSPACE 
 chmod a+x eclipse-$WORKSPACE
fi
