= Terms of Use

We provide the computer program of devon-ide, (hereinafter "Software") free of charge to download. Regarding this software the license terms of the Apache License 2.0 apply. The user shall be responsible to provide the required system environment for using the software. In accordance with the license terms of the Apache License 2.0, the user is entitled to use the Software in own / other projects (also commercial projects), provided that the copyright notice will be taken.

The software also requires open-source components of third-parties (providers), for which the respective open source license terms apply. The open-source components of third parties are not from us and must be licensed directly from the respective third party. The rights to use will be granted directly by the respective right owner to the extent of each relevant open source license terms. The user himself can download the desired third party component from the servers of the respective provider and install them in his own environment.

The third-party components directly required to run devon-ide-configurator are included in the `scripts/lib` folder. Before using this software please read the licenses carefully and ensure you agree with all of them. You can find them in the `scripts/licenses` folder. An overview of the libraries with their licenses is given in link:scripts/licenses/THIRD-PARTY.txt[THIRD-PARTY.txt]. To be compliant with the third-party licenses we include the source-code of the third-party components in `scripts/licenses/sourcecode`.

