#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup help"
  fi
  exit
fi

if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions

# Call aws with specified arguments.
function doRun() {
  doSetup silent
  doRunCommand "aws ${*}"
}


# OS independent check if aws is installed.
function doIsAwsInstalled() {
  if command -v aws &> /dev/null
  then 
    return
  else
    return 255
  fi
}

# $1: path_to_package
# $2: software version
function doPackageInstall()
{
  local path_to_package="${1}"
  local version="${2}"
  if doIsWindows
  then
    doEcho "Installing AWS for Windows..."
    windows_path_to_package=$(cygpath -w "${path_to_package}")
    powershell.exe -Command "Start-Process msiexec.exe -verb runas -Wait -ArgumentList '/I ${windows_path_to_package}\aws-${version}-windows.msi /quiet'"
  elif doIsMacOs
  then
    doFail "Sorry, AWS CLI installation support is not yet implemented for your OS. Please install manually or help devonfw-ide to support it for your OS by contributing a pull-request."
  else
    doEcho "Installating AWS for Linux..."
    doRunCommand "sudo ${path_to_package}/install"
  fi
  doRunCommand "rm -rf ${path_to_package}"
}

function doSetup() {

  if [[ $(command -v aws) != "/c/Program Files/Amazon/AWSCLIV2/aws" ]] || [ "${1}" != "silent" ] 
  then
    # Get leatest release
    if [ -z "${AWS_VERSION}" ]
    then
      doEcho "Getting latest release..."
      AWS_VERSION=$(curl "https://github.com/aws/aws-cli/tags" | awk -F'tags/' '/archive/ { print $2}' | sort -r | head -1 | awk -F'.zip' '{print $1}')
    fi

    doInstall "-" "${DEVON_IDE_HOME}/updates/install/aws" "aws" "${AWS_VERSION}" 
    if [ "${?}" = 0 ]
    then
      doPackageInstall "${DEVON_IDE_HOME}/updates/install/aws" "${AWS_VERSION}" 
    fi

    if [ "${1}" != "silent" ] && ! doIsQuiet
    then
      doEcho "logon again to test aws with \"aws --version\""
    fi 
  fi
}


# CLI
case ${1} in 
"help" | "-h")
  echo "Setup or run AWS CLI (command-line interface for Amazon-Web-Services)."
  echo
  echo "Arguments:"
  echo " setup                    install aws on your machine."
  echo " <<args>>                 call aws with the specified arguments. Call aws --help for details or use aws directly as preferred."
  echo
;;
"setup" | "s" | "")
  doSetup
;;
*)
  doRun "${@}"
;;
esac
