= Windows Integration

This folder contains configurations to integrate `devon-ide` into MacOS.

== CMD
If you want to open a `CMD` (MS Dos Shell) directly from `Windows Explorer` for a folder in your `devon-ide` project you will also want to have the environment variables set properly so that you can run `mvn`, `yarn`, `gulp`, or whatever directly from that shell. Therefore you once have to follow these steps:

* Right-click on the file `IDEenv.reg` from `cmd` sub-folder and choose `Merge` from Context-Menu.
* Confirm the dialog `User Account Control` with `Yes`.
* Confrim the dialog `Registry Editor` with `Yes`.
* Click `OK`.

Now you have the option `Open Devon CMD here` if you right click on a folder in `Windows Explorer` that will open `CMD` and automatically setup your environment according to the `devon-ide` project containing the folder (if any, see above).

=== ConEMU
https://conemu.github.io/[ConEmu] is a great extension that brings additional features such as tabs to your windows shells. If you like it, you will also want to have it integrated with `devon-ide`. All you need to do is follow these simple steps:

* Copy the file `CmdInit.cmd` from your ConEmu installation (`C:\Program Files\ConEmu\ConEmu\CmdInit.cmd`) to a personal folder (e.g. `C:\Users\MYLOGIN\scripts`).
* Modify this copy of `CmdInit.cmd` by adding the line `IDEenv` (e.g. at line 6) and saving.
* Go to `ConEmu` and open the `settings` (via context menu or `[Windows][Alt][p]`).
* Select `Startup > Tasks` from the left tree.
* Select the first option form `Predefined tasks (command groups)` (`{Shells::cmd}`)
* In the text area at the right bottom modify the location of `CmdInit.cmd` to your customized copy (`%HOME%\scripts\CmdInit.cmd`).
* Select `Integration` from the left tree.
* Click on the upper `Register` button (for `ConEmu Here`).
* Click on `Save settings`

Now you have the option `ConEmu here` if you right click on a folder in `Windows Explorer` that will open a new tab in `ConEmu` and automatically setup your environment according to the `devon-ide` project containing the folder (if any, see above).

=== ConEMU and StartExplorer

You can even integrate the Eclipse StartExplorer plug-in and ConEMU to open up console right from the file tree of eclipse into ConEMU. You can do this by adding a custom command to StartExplorer:

1. Open up eclipse
2. Open Window > Preferences
3. Select StartExplorer > Custom Commands on the left
4. Add on the right and setup the following command: `"C:\Program Files\ConEmu\ConEmu64.exe" -Dir ${resource_path} -runlist cmd.exe /k ""%ConEmuBaseDir%\CmdInit.cmd" & "IDEenv"" -cur_console:n`
Be aware that you potentially have to adapt the `ConEmu*.exe` path to match your installation.
+
You can even add a shell login if you installed git bash on your machine. Please be aware to potentially adapt the `sh.exe` url to match your installation: `"C:\Program Files\ConEmu\ConEmu64.exe" -Dir ${resource_path} -runlist cmd.exe /k ""%ConEmuBaseDir%\CmdInit.cmd" & "IDEenv" & "%SYSTEMDRIVE%\Program Files\Git\bin\sh.exe" --login" -cur_console:n` 
5. State two times the "Name for *" to your choice like "ConEMU"
6. OK -> OK
7. Right click on any folder/file in your eclipse file explorer and select StartExplorer > Custom Commands > ConEMU.
8. You will get a initialized console at the file/folder location! Have fun!

=== Cygwin
Ensure to have `chere` installed in cygwin. Otherwise go the cygwin setup and install it. Then run a cygwin terminal as administrator and call this command: `chere -i -t mintty`. Now you will have the option `Bash Prompt Here` in your WindowsExplorer context menu. 

In order to integrate with `devon-ide` you simply have to source add the line `. ~/IDEenv.sh` this to your `~/.bashrc`.
The `IDEenv.sh` shall be located in your unix home directory (`~/IDEenv.sh`) with this content:
[source,bash]
--------
CWD=$PWD
while ! [ -e scripts/environment-project.sh ] && [ "$PWD" != "/" ]
do
  cd ..
done
if [ -e scripts/environment-project.sh ]
then
  . scripts/environment-project.sh
fi
cd $CWD
--------
