:toc:
toc::[]

= Azure CLI

The Azure CLI commandlet allows to install and use https://github.com/Azure/azure-cli[Azure CLI].
Call `devon az «args»` is more or less the same as calling `az «args»` but with some advanced features and ensuring that Azure CLI is properly set up for your project.

*ATTENTION:*
Currently this feature is new and therefore experimental.
It may change in incompatible ways in the next releases until we reach a stable state.
We hope that all is working fine for you.
However, do not expect everything to work out of the box.

The arguments (`devon az «args»`) are explained by the following table:

.Usage of `devon az`
[options="header"]
|=======================
|*Argument(s)*|*Meaning*
|`setup`      |setup Azure CLI (install and verify) as per above flow.
|`«args»`     |call Azure CLI with the specified arguments. Call `az help` for details or use `az` directly as preferred." (`«args»`)
|=======================

== Configuration File
The configuration file is located at `conf/.azure`.
Don't forget to set the environment variables of your IDE with `devon` before setting new configurations for Azure.

