:toc:
toc::[]

= Configuration

The `devon-ide` aims to be highly configurable and flexible. The configuration of the link:cli[devon] command and environment variables takes place via `devon.properties` files. The following list shows these configuration files in the order they are loaded so files can override variables from files above in the list:

0. build in defaults (for `JAVA_VERSION`, `ECLIPSE_PLUGINS`, etc.)
1. `https://github.com/devonfw/devon-ide/blob/master/scripts/src/main/resources/scripts/devon.properties[scripts/devon.properties]` - defaults provided by `devon-ide`. Never directly modify this file!
2. `devon.properties` - vender variables for custom distributions, may e.g. tweak `SETTINGS_PATH` or predefine `SETTINGS_URL`.
3. `https://github.com/devonfw/devon-ide/blob/master/settings/src/main/settings/devon/devon.properties[settings/devon.properties]` (`$SETTINGS_PATH/devon.properties`) - project specific configurations from link:settings[].
4. `workspaces/${WORKSPACE}/devon.properties` (`$WORKSPACE_PATH/devon.properties`) - optional workspace specific configurations (espeically helpful in projects using docker).
5. `https://github.com/devonfw/devon-ide/blob/master/settings/src/main/settings/devon/conf/devon.properties[conf/devon.properties]` - user specific configurations (e.g. `M2_REPO=~/.m2/repository`). During setup this file is created by copying a template from `$SETTINGS_PATH/devon/conf/devon.properties`.

== devon.properties

The `devon.properties` files allow to define environment variables in a simple and OS independent way:

* `# comments begin with a hash sign (#) and are ignored`
* `variable_name=variable_value with space etc.`
* `variable_name=${predefined_variable}/folder_name`
+
variable values can refer to other variables that are already defined what will be resolved to their value. You have to used `${...}` syntax to make it work on all platforms (never use `%...%`, `$...`, or `$(...)` syntax in `devon.properties` files).
* `export exported_variable=this value will be exported in bash, in windows CMD the export prefix is ignored`
* `variable_name=`
+
this will unset the specified variable
* `variable_name=~/some/path/and.file`
+
tilde is resolved to your personal home directory on any OS including windows.
* `array_variable=(value1 value2 value3)`
+
This will only work properly in `bash` worlds but as no arrays are used in CMD world of `devon-ide` it does not hurt on windows.
* Please never suround values with quotes (`var="value"`)
* This format is similar to Java `*.properties` but does not support advanced features as unicode literals, multi-lined values, etc.

In order to know what to configure have a look at the available link:variables[].

Please only tweak configurations that you need to change and take according responsibility. Flexibiltiy comes with some price. Of course you can break everything if you do the wrong things.

Further, you can configure link:mvn[maven] via `conf/settings.xml`. To configure your IDE such as link:eclipse[] or link:vscode[] you can tweak the link:settings[].