:toc:
toc::[]

= Getting started as developer contributing to devonfw-ide

== Installation
To start developing devonfw-ide, you must first install it on your computer.
Therefore simply follow the link:setup.asciidoc[setup] guide.

== Contribution
To begin, read through the https://github.com/devonfw/.github/blob/master/CONTRIBUTING.asciidoc[Contribution Guidelines], which you should be sure to follow.
First steps regarding forks or cloning of repos and creating branches, as well as some git commands, https://github.com/firstcontributions/first-contributions[can be found here].
Clone the https://github.com/devonfw/ide[project IDE] at the beginning.
For further development and testing, it is recommended to copy the modified scripts into your devonfw-ide installation.
Alternatively, the scripts can be adapted in the installation folder and then committed to the project.

=== ShellCheck

To improve the code quality the https://github.com/koalaman/shellcheck/[ShellCheck] is used for devon-ide.
There is a GitHub action _CI build PR_ for this. If this fails at the PR, you can find the error messages in the big logfile under _Build project with Maven_.
For example, these look like this:

```
Running test #2: test-shellcheck

In scripts/functions line 659:
    doUnzip ${1} ${target_dir}
            ^--^ SC2086: Double quote to prevent globbing and word splitting.
                 ^-----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    doUnzip "${1}" "${target_dir}"

For more information:
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...

```

Further explanations for ShellCheck errors can be found in the https://www.shellcheck.net/wiki/[ShellCheck Wiki].
Own code can also be tested with the https://www.shellcheck.net/[Online ShellCheck].
ShellCheck can also be run on the local development environment. To do this, ShellCheck (https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.zip[win], https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.darwin.x86_64.tar.xz[mac]) can be extracted to the program directory. For windows the path to the executable (`C:\Program Files\shellcheck-stable`) must be written to the path (https://medium.com/@kevinmarkvi/how-to-add-executables-to-your-path-in-windows-5ffa4ce61a53[instruction]). In the resource folder of the project (`scripts/src/main/resources`) the following command can now be executed in the git-bash:

```
shellcheck.exe -x -e SC2181 setup scripts/devon scripts/environment-project scripts/functions scripts/command/*
```

For Mac and Linux, ShellCheck is automatically called during the build process (`mvn install`).

== Create a new commandlet

=== IDE-Mirrors
Many programs have a download link that depends on the operating system. 

For a new tool create a folder in https://github.com/devonfw/ide-mirrors[ide-mirrors] repository with its name containing the following files:

* `urls` contains the download URL(s) that typically contain placeholders like `${ext}` for extension, `${os}` for operating-system, `${arch}` for CPU architecture, or `${code}` for commandlet specific things. The file can hold multiple URLs - one per line. This is used if multiple https://en.wikipedia.org/wiki/Mirror_site[mirrors] are available so the load gets distributed. Therefore devonfw-ide will shuffle the URLs into random order and then try them sequentially so if one URL does not work (e.g. mirror unavailable) it will try the next one.
* `ext-mapping` contains the mapping from operating system (OS) to the according file extension filled into the `${ext}` placeholder of the download for that OS.
* `os-mapping` contains the remapping from OS to the value filled into the `${os}` placeholder of the URL. So you can e.g. remap `windows=win` or `mac=darwin` in case the download URLs do not follow common practices. You can even omit this file to fall back to the default https://github.com/devonfw/ide-mirrors/blob/master/os-mappings[os-mappings].
* `arch-mapping` contains the remapping from architecture to the value filled into the `${arch}` placeholder of the URL. So you can e.g. remap `aarch64=arm64` or `x86_64=x64` in case the download URLs do not follow common practices. Simply omit this file if not needed.
* `versions` in very special cases, you can create separate configurations in sub-folders for specific versions or version-ranges. Here you can specify a folder-name followed by a less-sign (`<`) and a version number to specify that if the version to install is less than this given version, the configuration will be read from that specified folder. The lines are processed top-down where the first match applies. An example can be found https://github.com/devonfw/ide-mirrors/blob/master/java/versions[here].

It is important that the line endings of all files are UNIX `\n`.

Note that all rules within a mapping are checked from top to bottom.
If the first rule matches, the other rules are ignored. Therefore, the *-rule should always be last.
With the `os-mapping` the *-rule should be used for the Linux distributions, since the OS type is not only linux, but varies strongly.

It is also possible to use variables in the mapping files. 
For example, if the architecture in the download link only appears for Windows, `{arch}` can be used in the `os-mapping`.

=== Commandlet
Use an existing commandlet like https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/command/helm[HELM] as a reference.
Create a file with the name of the tool and put it in the folder https://github.com/devonfw/ide/tree/master/scripts/src/main/resources/scripts/command[scripts/command].
The first part of the script contains the autocompletion, which should return the available parameters.
Functions like setup or run or other additional functions follow.
Finally, it defines which function should be executed depending on the parameter.

Use the `doInstall` method for the installation, which downloads the tool based on the mirrors, unpacks it if necessary and puts it in the software folder in the `devonfw-ide` installation:
```
doInstall "-" "«installation-folder»" "«tool-name»" "«tool-version»"
```

=== LICENSE
Find the license for the new tool and add the tool to the table of `Third party components` of the link:LICENSE.asciidoc[LICENSE].
If the license itself does not exist, add it to the end of the file as a new section.

== Settings
The https://github.com/devonfw/ide-settings[ide-settings] repository allows project-specific configurations of the IDE tools.
For your own settings, fork the repository, adjust the configuration and specify the repository URL during installation.
Important notes on configuration and especially configuration files can be found in the link:configuration.asciidoc[configuration].
In the configuration files many link:variables.asciidoc[variables] can be defined.

== Tipps and tricks

=== Symbolic Links to ease testing and commiting in Windows

With https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html[symbolic links] you can use one file that is located inside one directory in multiple other directories, without copying the whole file the the other directories. The file is still only saved at the initial location, but can be accessed through the  created links in a much more comfortable way. So you are actually just linked to the original file and therefore don't have to worry about differing versions of the file in your directory. This is very helpful for testing our devon-ide, because e.g. the commandlets folder for testing is not the same as the commandlets folder for git-commits. 
Follow https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html[these] installation and usage instructions first. 
Later on you can make symbolic links of files from your "git folder" and add them into the folder in which the testing is supposed to take place.
E.g. make a symbolic link of "${DEVON_IDE_HOME}/workspaces/ide/scripts/src/main/resources/scripts/command/docker" and insert it into the folder "${DEVON_IDE_HOME}/scripts/command".
Now changes you make in the first mentioned file  will directly be available in your testing environment.

=== developer tools

* Simple Tab Groups: Firefox plugin that helps to separate tabs e.g. tabs for projekt A, projekt B, travelplanning or hobbies 
* gitfork: Tool for Windows and Mac that makes working with git easier and gives a better overview compared to just using a shell 
* https://www.heise.de/tipps-tricks/SSH-unter-Windows-10-nutzen-4224757.html[Windows Terminal]: A tool that enables the user to use CLIs of various kinds like git-bash, Powershell, CMD, WSL-Shells or Putty



=== Bash (Linux's Borne Again Shell)
**For beginners:**

You probably know this black box on Windows (the Command Prompt) that accepts commands like 'dir' that shows the content of the directory you are currently in,
or 'cd' with which you can change the directory you are currently in and many more commands that allow you to interact with your Windows Operating System in a more direct and eventually faster way.  
Now for users of a Linux Distribution there is something similar, but way more powerfull, usually called "Bourne Again Shell", or in short Bash.
This Command Line Interface or "Shell" is what we use most often when implementing something new for our Command-Line-Tool with the name devonfw-ide.  https://www.youtube.com/watch?v=I4EWvMFj37g[Have a look at Bash in 150 Seconds.]
For MacOS you often also use BASH.
That's why it is often enough to implement code for Mac or Linux (at least to some extend as you'll see soon enough) to be able to use it on both Operating Systems.

Let's get to the practical part of the Bash-usage. 

**If you are using Windows**, make sure that you have git-bash installed, so you can execute the Bash commands mentioned in this intruduction. [Here you can find git for windows](https://git-scm.com/download/win). In some cases later on you may want or need to use WSL. Our project teams standard way is to install WSL via Rancher Desktop, which is easily installable with the devon-ide by using the command `devon docker setup`. If you don't have the devon-ide yet, then you can follow [this guide](https://github.com/devonfw/ide/blob/master/documentation/setup.asciidoc)

Now I want to share a good and rather short video for Bash-beginners with you.
In https://www.youtube.com/watch?v=oxuRxtrO2Ag[this robust introduction] , where you will be going through some of the most important commands and concepts in round about 70 Minutes (you can find a list of the commands introduced there at the videos description).
There are some really usefull commands, that I would have liked to know back then when I started with Bash.  
When you have learned the knowledge from this video, then you'll be a big step further on your journey with Bash. 
It is really worth watching such a video while simultaneously directly playing around with those commands on your own Shell.
This makes the learning process faster and also way more interesting than simply reading or listenning to such a tutorial.  

When you used to program in some other languages, you for sure know how helpful a google search in combination with the results on stackexchange can be.
If not, then google your question regarding Bash as usual and mostly you'll find a way to get together the code you want. 
Sometimes it needs more patience to get an acceptable result or to find out that a command you already knew includes what you need, if you add the proper tag to its execution.
Take the commands and some of their tags mentioned in https://www.freecodecamp.org/news/linux-command-line-Bash-tutorial/[this rather brief tutorial] as an example. Also definetely try to use the help function from time to time, e.g. type in `ls --help` and you'll see how much more the command `ls` can offer. 
On the other side, especialy at the beginning, it is better to get an overview of available tags by googling e.g. 
*ls tags Bash* to get a way prettier overview plus examples regarding a commands tags like https://www.tecmint.com/15-basic-ls-command-examples-in-linux/[here] for `ls`.

**If you have some experience with the Bash or directly want to see more:**

The meaning of a tag or a sign combination (like `$*`, `$#`, or `$()`) can be hard to guess and also less easy to find during a google-search, because google won't directly search for signs.
Then a syntax cheatsheet https://www.pcwdld.com/bash-cheat-sheet[like this] or https://devhints.io/bash[like that one] can spare you some searching time. 
If you don't know what a positional parameter like `$1` is in Bash, then have a look at https://wiki.bash-hackers.org/scripting/posparams[this introduction] and play around with the tools mentioned to get a better understanding of how they work.
It's definitively worth knowing the basics about positional parameters if you want to make some more advanced Bash-scripts.
There are a few more topics that I want to mention to you as you may come across them regularly in Bash-scripting. 
The first one concerns regular expressions, which you will find during various coding situations.
Therefore have a look at https://tldp.org/LDP/abs/html/x17129.html[this rather short introdcution on regex] if you are unfamiliar with the so called regex. 
Another one is about if-statements and square brackets for testing expressions by comparing them in different ways.
Maybe you'll find something new or helpful https://ryanstutorials.net/bash-scripting-tutorial/bash-if-statements.php[here]. 
Finally, to possibly increase your knowledge while scripting bash-files, try out https://www.shellcheck.net/[this spellchecker] that can give you many details on how to improve your code.

**Directly regarding our project:**

In case you want to get your hands dirty with code that is already in use and comes from our ide-project, then you can try out the functions written in our https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/functions[functions-file]. 
There are also some basic exercises related to our project that are not official yet, but you can ask for if you want to try some of them out to learn and challenge yourself a bit.

== Documentation
https://devonfw.com/website/pages/docs/devonfw-guide_ide.wiki_devonfw-ide.asciidoc.html
