:toc:
toc::[]

= Introduction

A common problem with eclipse plugins is that they are provided decentralized as so-called update-sites via URLs. The maintainer of that URL is in full control of the availability and the content behind that URL. If the service gets broken, obviously the plugin can not be downloaded. Even worse if existing content gets updated, the result is not reproducible anymore. 

All famous IDEs do not have a clear versioning concept: While the plugin artifact itself is typically versioned, the request to install a plugin can not specify a version but always downloads the "latest" version. If at all some kind of versioning for stability is in place it happens via the URL itself so for different major versions different URLs are provided.

A possible solution is to mirror the update sites and store them either locally or on your own webspace. This way you always have access to the plugin version you need as a developer without being dependent on the plugin providers.

Below is the process to mirror a plugin update site. 

== Mirroring Eclipse Update Sites

For mirroring you need to things: 

1. URL of the update-site (e.g. http://download.jboss.org/jbosstools/updates/webtools/photon/)
2. Plugin-ID (e.g org.eclipse.core.runtime)

Open any CLI in your IDE folder and execute the following command.

`devon eclipse download-plugin <Plugin-ID> <URL>`

This command will automatically download all important files to a folder.
