= Integration

The `devonfw-ide` already brings a lot of integration out of the box. This page is for users that want to get even more out of it. For instance this IDE ships with a `console` script to open a shell with the environment variables properly set for your `devonfw-ide` installation, so you get the correct version of your tools (Java, Maven, Yarn, etc.). However, you might want to open a shell from your IDE or your file manager. For some of these use-cases you need additional tweaks that are described on this page.

== Windows
devonfw-ide automatically integrates with Windows-Explorer during link:setup.asciidoc[setup].

=== CMD
If you want to open a `CMD` (MS Dos Shell) directly from `Windows-Explorer` simply right-click on the  folder in your `devonfw-ide` you want to open. From the context menu click on `Open Devon CMD shell here`. This will open `CMD` and automatically initialize your environment according to the `devonfw-ide` project containing the folder (if any, see above).

=== Git-Bash
Just like for `CMD` you can also click `Git Bash Here` from Windows-Explorer context-menu to open a git bash. If you have selected a folder in your `devonfw-ide` installation, it will automatically initialize your environment.

=== Cygwin
In case you have `cygwin` installed on your machine, the `devonfw-ide` will autodetect this during `setup` and also install a `Windows-Explorer` integration. Just choose `Open Devon Cygwin Bash Here` to open cygwin bash and initialize your `devonfw-ide` environment.

=== ConEMU
https://conemu.github.io/[ConEmu] is a great extension that brings additional features such as tabs to your windows shells. If you like it, you will also want to have it integrated with `devonfw-ide`. All you need to do is follow these simple steps:

* Copy the file `CmdInit.cmd` from your ConEmu installation (`C:\Program Files\ConEmu\ConEmu\CmdInit.cmd`) to a personal folder (e.g. `C:\Users\MYLOGIN\scripts`).
* Modify this copy of `CmdInit.cmd` by adding the line `IDEenv` (e.g. at line 6) and saving.
* Go to `ConEmu` and open the `settings` (via context menu or `[Windows][Alt][p]`).
* Select `Startup > Tasks` from the left tree.
* Select the first option form `Predefined tasks (command groups)` (`{Shells::cmd}`)
* In the text area at the right bottom modify the location of `CmdInit.cmd` to your customized copy (`%HOME%\scripts\CmdInit.cmd`).
* Select `Integration` from the left tree.
* Click on the upper `Register` button (for `ConEmu Here`).
* Click on `Save settings`

Now you have the option `ConEmu here` if you right click on a folder in `Windows Explorer` that will open a new tab in `ConEmu` and automatically setup your environment according to the `devonfw-ide` project containing the folder (if any, see above).

=== ConEMU and StartExplorer

You can even integrate the Eclipse StartExplorer plug-in and ConEMU to open up console right from the file tree of eclipse into ConEMU. You can do this by adding a custom command to StartExplorer:

1. Open up eclipse
2. Open Window > Preferences
3. Select StartExplorer > Custom Commands on the left
4. Add on the right and setup the following command: `"C:\Program Files\ConEmu\ConEmu64.exe" -Dir ${resource_path} -runlist cmd.exe /k ""%ConEmuBaseDir%\CmdInit.cmd" & "IDEenv"" -cur_console:n`
Be aware that you potentially have to adapt the `ConEmu*.exe` path to match your installation.
+
You can even add a shell login if you installed git bash on your machine. Please be aware to potentially adapt the `sh.exe` url to match your installation: `"C:\Program Files\ConEmu\ConEmu64.exe" -Dir ${resource_path} -runlist cmd.exe /k ""%ConEmuBaseDir%\CmdInit.cmd" & "IDEenv" & "%SYSTEMDRIVE%\Program Files\Git\bin\sh.exe" --login" -cur_console:n` 
5. State two times the "Name for *" to your choice like "ConEMU"
6. OK -> OK
7. Right click on any folder/file in your eclipse file explorer and select StartExplorer > Custom Commands > ConEMU.
8. You will get a initialized console at the file/folder location! Have fun!

== Eclipse
You might want to open a terminal directly as view inside your Eclipse IDE. Therefore we provide link:eclipse.asciidoc[eclipse] with the http://marketplace.eclipse.org/content/tm-terminal[TM terminal] plugin.
Further the link:settings.asciidoc[settings] already configure that plugin so it automatically sets the environment properties correctly. In other words the integration comes out of the box.

To use it all you need to do is to follow these steps:

* Open the `Terminal` view (`Window > Show View > Other > Terminal > Terminal > OK`). 
* Click on the `monitor icon` from the left of the icon bar of the `Terminal` view.
* Choose terminal (e.g. `Local Terminal`) and confirm with `OK`
* Execute `mvn -v` to verify your environment.

== IntelliJ or WebStorm
You might want to open a terminal directly as view inside your IDEA IDE, that already ships with a feature for this out of the box.
If you start your IDE via the `start-idea` script provided by `devonfw-ide` then everything is configured and your environment is set automatically.
