:toc:
toc::[]

= java

The `java` commandlet allows to install and setup https://openjdk.java.net/[Java]. Also it supports https://github.com/devonfw/devon4j[devon4j].
The arguments (`devon java «args»`) are explained by the following table:

.Usage of `devon java`
[options="header"]
|=======================
|*Argument(s)*                       |*Meaning*
|`setup`                             |setup OpenJDK (install or update and verify), link:configuration.asciidoc[configurable] via `JAVA_VERSION` (e.g. `8u242b08` or `11.0.6_10`)
|`create «args»`                     |create a new Java project. You can choose between Quarkus and Spring. Spring creation is based on https://github.com/devonfw/devon4j/blob/master/documentation/tutorial-newapp.asciidoc[devon4j application template]. If a single argument is provided, this is the package name and is automatically split into groupId and artifactId for Spring. To select a framework use the -f parameter with the choosen framework. Use `-DdbType=«db»` to choose the database for both frameworks (hana, oracle, mssql, postgresql, mariadb, mysql, h2, hsqldb). Any option starting with dash is passed as is." 
|`migrate [from «version»] [single]` |migrate a https://github.com/devonfw/devon4j[devon4j] project to the latest version. If for some reasons the current devonfw version can not be auto-detected you may provide it manually after the 'from' argument. Also the 'single' option allows to migrate only to the next available version."
|`cicd «args»`                       |generate cicd files for the current devon4java project
|=======================

== create
With the create command you can choose to create a spring or a Quarkus application. 
```
devon java create
```
With this command you will be guided throught the project creation and you will have to pass some additional information.

Choosing the framework can be done with 
```
-f spring or -framework quarkus
```

=== Spring 
Examples for create a new devon4j spring application:
```
devon java create -f spring
```
Will create a spring app, command line will ask for atleast a packagename.

```
devon java create com.example.domain.myapp
```
```
devon java create -f spring com.example.domain.myapp 
```
Will both create an app with package `com.example.domain.myapp`, groupId `com.example.domain`, artifactId `myapp`, version `1.0.0-SNAPSHOT`, and h2 database.
```
devon java create -Dversion=0.0.1-alpha1 com.example.domain.myapp
```
Will create an app with package `com.example.domain.myapp`, groupId `com.example.domain`, artifactId `myapp`, version `0.0.1-alpha1`, and h2 database.

```
devon java create com.example.domain.myapp com.example.group
```
Will create an app with package `com.example.domain.myapp`, groupId `com.example.group`, artifactId `myapp`, version `1.0.0-SNAPSHOT`, and h2 database.

```
devon java create com.example.domain.myapp com.example.group demo-app
```
Will create an app with package `com.example.domain.myapp`, groupId `com.example.group`, artifactId `demo-app`, version `1.0.0-SNAPSHOT`, and h2 database.

```
devon java create com.example.domain.myapp -DartifactId=demo-app -DdbType=hana
```
Will create an app with package `com.example.domain.myapp`, groupId `com.example.group`, artifactId `demo-app`, version `1.0.0-SNAPSHOT`, and SAP hana database.

```
devon java create com.example.domain.myapp -DdbType=oracle -Dversion=0.0.1 com.example.group -Dbatch=batch
```
Will create an app with package `com.example.domain.myapp`, groupId `com.example.group`, artifactId `myapp`, version `0.0.1`, oracle database, and with a batch module.

The -f parameter can be added to every command.

=== Quarkus 
Examples for create a new devon4j Quarkus application:
```
devon java create -f quarkus
```
You have to pass a https://code.quarkus.io/ link with the project information to the command line. The package, artifactId and version can be set in the quarkus code creation.
```
devon java create -f quarkus -Ddbtype=postgresql
```
Will create a app with also a postgresql database.


== migrate
Example for migrating a devon4j application:
```
devon java migrate
```
Will migrate current devon4j application to the latest version available.
