:toc:
toc::[]

= Kubernetes

The `kubectl` commandlet allows to install and use https://kubernetes.io/[kubernetes].
On Windows https://docs.microsoft.com/en-us/windows/wsl/install-win10[WSL 2](Windows Subsystem for Linux) has to be installed properly as a prerequisite.
The setup on windows will then install kubernetes with https://k3d.io[K3D]. K3D will create a cluster with a single node with a default name as "devonfw-cluster"

*ATTENTION:*
Currently this feature is new and therefore experimental.
It may change in incompatible ways in the next releases until we reach a stable state.
We hope that all is working fine for you.
However, do not expect everything to work out of the box.
In case you are facing issues (e.g. network problems with Cisco AnyConnect, etc.) please give us feedback so we can improve.

The arguments (`devon kubectl «args»`) are explained by the following table:

.Usage of `devon kubectl`
[options="header"]
|=======================
|*Argument(s)*             |*Meaning*
|`setup`                   |setup Kubernetes (install and verify) as per above flow.
|`«args»`                  |call kubectl with the specified arguments. Call `kubectl help` for details or use kubectl directly as preferred.
|=======================

== setup
Please note that on Windows and macOS, Kubernetes support comes together with `Docker Desktop` that is installed via link:docker.asciidoc[docker] commandlet.
When you have installed and launched `Docker Desktop`, you can once https://docs.docker.com/desktop/kubernetes/#enable-kubernetes[enable Kubernetes in the Preferences].

On Linux however, Kubernetes is installed separately by this commandlet.

== usage
Once installed via setup, you can run `kubectl` directly from any shell of your OS directly.
Run `kubectl help` to get started and use the online documentations and resources on the web to get familiar with Kubernetes.
It is not our intention to repeat this here.

Please note that the `kubectl` commandlet is a link:cli.asciidoc#command-wrapper[command wrapper].
