:toc:
toc::[]

= Lombok

Even though not officially recommended by `devon4j` some projects want to use https://projectlombok.org/[lombok] in their project.
As this requires some tweaks for IDEs we do support you with this guide in case you want to use it.

== Lombok in Eclipse

For eclipse there is a plugin to activate https://projectlombok.org/setup/eclipse[lombok support in eclipse].
We have this already pre-configured for you in our default link:settings.asciidoc[settings]. So for manual installation after link:setup.asciidoc[setup], you can get it via this command: 
```
devon eclipse add-plugin lombok
```
However, to avoid manual extra effort for lombok based projects you only need to activate this plugin in your project specific link:settings.asciidoc[settings] in https://github.com/devonfw/ide-settings/blob/master/eclipse/plugins/lombok.properties#L3[lombok.properties for eclipse] (replace `false` with `true` for `plugin_active`).

== Lombok for VS-Code

For VisualStudio Code there is an extension to activate https://projectlombok.org/setup/vscode[lombok support in VS-Code].
We have this already preconfigured for you in our default link:settings.asciidoc[settings]. So for manual installation after link:setup.asciidoc[setup], you can get it via this command: 
```
devon vscode add-plugin lombok
```
However, to avoid manual extra effort for lombok based projects you only need to activate this plugin in your project specific link:settings.asciidoc[settings] in https://github.com/devonfw/ide-settings/blob/master/vscode/plugins/lombok.properties#L2[lombok.properties for vscode] (replace `false` with `true` for `plugin_active`).

== Lombok for IntelliJ

For IntelliJ there is a plugin to activate https://projectlombok.org/setup/intellij[lombok support in IntelliJ].
Currently we have not yet configured or automated this in `devonfw-ide`.
Please contribute to change this. See issues https://github.com/devonfw/ide/issues/453[#453] and https://github.com/devonfw/ide/issues/491[#491].
