:toc:
toc::[]

= migration

When we publish a new release, our users can install it to existing devonfw-ide installations via `devon ide update scripts`. 
Sometimes we do some structural changes and "pollute" our scripts/commandlets with legacy handling code. 
To avoid this behaviour, there is a `migration` script under `${DEVON_IDE_HOME}/scripts` that is automatically executed by `devon ide update scripts` but at the end on the new release.
The `migration` script checks the installed version of the updating ide and executes all xref:migration scripts[] under `${DEVON_IDE_HOME}/scripts/migrations`.

== migration scripts
The migrations folder has to follow this structure:

.Structure of migrations folder
[subs=+macros]
----
/migrations
├──/ ...
├──/ 2023.01.001
├──/ 2023.02.001
├──/ 2023.02.003
├──/ 2023.03.001 
├──/ 2023.03.002 
├──/ 2023.04.001
├──/ ...
----

As you can see, the migrations folder contains scripts with specific ide versions.
So if the user runs `devon ide update scripts` on ide with version `2023.01.001`, the `migration` script will execute each script in migrations folder from the same version to the latest version in numerical order.

ATTENTION: Since this feature is available with version ´2023.01.001´, older ide's are not affected by the migration.


