:toc:
toc::[]

= Python

The Python Commandlet allows to install and use the Python CLI and pip.

ATTENTION: Python support for different platforms is not great unfortunately.
On Linux and MacOS we have to build Python from the source-code during the installation as portable downloads are only available for windows.
However, on some Macs the configure script of Python fails.
This is not our fault and we can not fix this unless it gets fixed in Python itself.
For details see bug issue https://github.com/devonfw/ide/issues/834[#834].

The arguments (`devon python «args»`) are explained by the following table:

.Usage of `python`
[options="header"]
|=======================
|*Argument(s)*    |*Meaning*
|`setup`          |install python on your machine.
|`help`           |access additional help information.
|`version`        |Get version of currently installed Python version.
|`pip`            |Call pip.
|`pip3`           |Call pip3. (Windows only)
|`«args»`         |call python with the specified arguments."
|=======================
