:toc:
toc::[]

= scripts
This directory is the heart of the `devon-ide` and contains the required link:https://github.com/devonfw/devon-ide/tree/master/scripts/src/main/resources/scripts[scripts].

.File structure of the conf folder
[subs=+macros]
----
/scripts
├──/ https://github.com/devonfw/devon-ide/tree/master/scripts/src/main/resources/scripts/command[command]
│  ├── link:build[]
│  ├── link:eclipse[]
│  ├── link:gradle[]
│  ├── link:help[]
│  ├── link:ide[]
│  ├── link:intellij[]
│  ├── link:java[]
│  ├── link:jenkins[]
│  ├── link:mvn[]
│  ├── link:ng[]
│  ├── link:node[]
│  ├── link:npm[]
│  ├── link:release[]
│  ├── link:sonar[]
│  ├── link:vscode[]
│  └── link:yarn[]
├── link:devon[devon]
├── link:devon[devon.bat]
├── link:configuration[environment-project]
├── link:configuration[environment-project.bat]
├── link:functions[]
├── link:configuration[devon.properties]
----

The https://github.com/devonfw/devon-ide/tree/master/scripts/src/main/resources/scripts/command[command] folder contains the link:cli#commandlets[commandlets].
The https://github.com/devonfw/devon-ide/tree/master/scripts/src/main/resources/scripts/devon[devon] script is the key link:cli[command line interface] for `devon-ide`. For windows there is also https://github.com/devonfw/devon-ide/tree/master/scripts/src/main/resources/scripts/devon.bat[devon.bat] to be used in CMD or PowerShell.
As the `devon` link:cli[CLI] can be used as global command on your computer from any directory and gets link:install[installed] centrally it aims to be stable, minimal, and leightweight. The key logic to setup the environment variables is therefore in a separate script https://github.com/devonfw/devon-ide/tree/master/scripts/src/main/resources/scripts/environment-project[environment-project] and its Windows variant https://github.com/devonfw/devon-ide/tree/master/scripts/src/main/resources/scripts/environment-project.bat[environment-project.bat] inside this `scripts` folder.
The file https://github.com/devonfw/devon-ide/tree/master/scripts/src/main/resources/scripts/functions[functions] contains a collection of reusable bash functions. These are sourced and used by the link:cli#commandlets[commandlets].
Finally the `devon.properties` file contains defaults for the general link:configuration[] of `devon-ide`.
