:toc:
toc::[]

= Setup

== Prerequisites
We try to make it as simple as possible for you. However, there are some minimal prerequesites:

* You need to have a tool to extract `*.tar.gz` files (`tar` and `gzip`). On Windows use https://www.7-zip.org/[7zip]. On all other platforms this comes out of the box.
* You need to have https://git-scm.com[git] installed. On Windows download and install from  https://git-scm.com/download/win[here]. This also ships with `bash` and `curl` on Windows what also is required and should be present on all other platforms.

== Download
Releases of `devon-ide` are published to maven central. You can download them from https://repo.maven.apache.org/maven2/com/devonfw/tools/ide/devon-ide-scripts/[here]. 

== Install
Create a central folder like `C:\projects` or `/projects`. Inside this folder create a sub-folder for your new project such as `my-project` and extract the contents of the downloaded archive (`devon-ide-scripts-*.tar.gz`) into this new folder. Run the command `setup` in this folder (on windows just double click `setup.bat`).
That's all. To get started read the link:usage.asciidoc[usage].

== Uninstall
To "uninstall" your `devon-ide` you only need to call the following command:
```
devon ide uninstall
```
Then you can delete the `devon-ide` top-level folder(s) (link:variables.asciidoc[${DEVON_IDE_HOME}]).

The `devon-ide` is designed to be *not invasive* to your operating system and computer. Therefore it is not "installed" into your system in a classical way. Instead you just create a folder and extract the xref:download[downloaded] archive to it. Only specific prerequisites like `git` have to be installed regularly by you in advance. All other software resists just locally inside the folder of your `devon-ide`. However, there are the following excuses (what is reverted by `devon ide uninstall`):

* The `devon` command is copied to your home directory (`~/.devon/devon`)
* The `devon` alias is added to your shell config (`~/.bashrc` and `~/.zshrc`, search for `alias devon="source ~/.devon/devon"`).
* On Windows the `devon.bat` command is copied to your home directory (`%USERPROFILE%\scripts\devon.bat`)
* On Windows this `%USERPROFILE%\scripts` directory is added to the `PATH` of your user.
* The `devon-ide` will download third party software to your `~/Downloads` folder to reduce redundant storage.
