#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version help"
  fi
  exit
fi

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions
AWS_HOME="${DEVON_IDE_HOME}/software/aws"
TOOL_VERSION_COMMAND="${AWS_HOME}/aws --version"
# shellcheck source=scripts/commandlet-cli
source "$(dirname "${0}")"/../commandlet-cli

function setConfig() {
  local aws_config_file="${DEVON_IDE_HOME}/conf/.aws"
  local aws_config_export="export AWS_CONFIG_FILE=${aws_config_file}"
  if ! grep -q "${aws_config_export}" "${DEVON_IDE_HOME}/conf/devon.properties"
  then
    doRunCommand "${aws_config_export}"
    echo -e "\n${aws_config_export}" >> "${DEVON_IDE_HOME}/conf/devon.properties"
    doEcho "Location of AWS's configuration file is set to ${aws_config_file}"
  fi
}

# shellcheck source=scripts/commandlet-cli
source "$(dirname "${0}")"/../commandlet-cli

# Call aws with specified arguments.
function doRun() {
  doSetup silent
  doRunCommand "${AWS_HOME}/aws ${*}"
}

function doSetup() {
  # workaround as we are downloading the installer and not installing the software itself
  TOOL_VERSION_COMMAND="-"
  doInstall "aws" "${AWS_VERSION}" "${1}" "" "${AWS_HOME}"
  ERR="${?}"
  local version_to_install
  version_to_install=$(cat "${AWS_HOME}"/.devon.software.version)
  if ! doIsWindows && ! doIsMacOs
  then
echo
    if [ "${ERR}" = 0 ]
    then
     doRunCommand "${AWS_HOME}/install -i ${AWS_HOME} -b ${AWS_HOME}"
     rm -rf "${AWS_HOME}"/install "${AWS_HOME}"/dist
    fi
  fi
  if [ "${ERR}" = 0 ]
  then
    setConfig
    if [ "${1}" != "silent" ] && ! doIsQuiet
    then
      TOOL_VERSION_COMMAND="${DEVON_IDE_HOME}/software/aws/aws --version"
      doRunCommand "${TOOL_VERSION_COMMAND}" "verify installation of aws"
    fi
  fi
}

# CLI
case ${1} in
"help" | "-h")
  echo "Setup or run AWS CLI (command-line interface for Amazon-Web-Services)."
  echo
  echo "Arguments:"
  echo " setup                          install aws on your machine."
  echo " «args»                         call aws with the specified arguments. Call aws --help for details or use aws directly as preferred."
  echo
;;
"setup" | "s" | "")
  doSetup "${2}"
;;
*)
  doRun "${@}"
;;
esac
