#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version help"
  fi
  exit
fi

if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
# OS independent check if aws is installed.
function findAws() {
  AWS="aws"
  AWS_INSTALLED="no"
  if command -v aws &> /dev/null
  then
    AWS_INSTALLED="yes"
  elif [ "${OSTYPE}" = "cygwin" ] || [ "${OSTYPE}" = "msys" ] # we can not use doIsWindows here as called before functions
  then
    local aws_win
    aws_win="${PROGRAMFILES}"
    aws_win="$(cygpath "${aws_win}")"
    aws_win="${aws_win}/Amazon/AWSCLIV2/aws"
    if [ -f "${aws_win}" ]
    then
      AWS="${aws_win}"
      AWS_INSTALLED="yes"
    fi
  fi
  TOOL_VERSION_COMMAND="'${AWS}' --version"
}

findAws
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions

# Call aws with specified arguments.
function doRun() {
  doSetup silent
  findAws
  doRunCommand "'${AWS}' ${*}"
}

# $1: path_to_package
function doPackageInstall() {
  local path_to_package="${1}"
  if doIsWindows
  then
    doEcho "Installing AWS for Windows..."
    windows_path_to_package=$(cygpath -w "${path_to_package}")
    powershell.exe -Command "Start-Process msiexec.exe -verb runas -Wait -ArgumentList '/I ${windows_path_to_package}\aws-*-windows.msi /quiet'"
  elif doIsMacOs
  then
    doEcho "Installing AWS for MacOS..."
    sudo installer -pkg "${path_to_package}"/aws-"${version}"-mac.pkg -target /
  else
    doEcho "Installating AWS for Linux..."
    if [ -L "/usr/local/bin/aws" ]
    then
      doRunCommand "sudo ${path_to_package}/install -u"
    else
      doRunCommand "sudo ${path_to_package}/install"
    fi
  fi
}

function doSetup() {
  if [ "${AWS_INSTALLED}" == "yes" ]
  then
    if [ -z "${1}" ]
    then
      doEcho "Aws already installed in version ${AWS_VERSION:-latest}"
      doRunCommand "${TOOL_VERSION_COMMAND}" "verify installation of aws"
    fi
  else
    # workaround as we are downloading the installer and not installing the software itself
    TOOL_VERSION_COMMAND="-"
    doInstall "aws" "${AWS_VERSION}" "${1}" "" "${DEVON_IDE_HOME}/updates/install/aws"
    if [ "${?}" = 0 ]
    then
      doPackageInstall "${DEVON_IDE_HOME}/updates/install/aws"
      findAws
      if [ "${1}" != "silent" ] && ! doIsQuiet
      then
        doRunCommand "${TOOL_VERSION_COMMAND}" "verify installation of aws"
      fi
    fi
    doRunCommand "rm -rf ${DEVON_IDE_HOME}/updates/install/aws"
  fi
}

# CLI
case ${1} in
"help" | "-h")
  echo "Setup or run AWS CLI (command-line interface for Amazon-Web-Services)."
  echo
  echo "Arguments:"
  echo " setup                          install aws on your machine."
  echo " «args»                         call aws with the specified arguments. Call aws --help for details or use aws directly as preferred."
  echo
;;
"setup" | "s" | "")
  doSetup "${2}"
;;
*)
  doRun "${@}"
;;
esac
