#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version help"
  fi
  exit
fi

if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
TOOL_VERSION_COMMAND="aws --version"
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions

# Call aws with specified arguments.
function doRun() {
  doSetup silent
  findAws
  doRunCommand "'${AWS}' ${*}"
}


# OS independent check if aws is installed.
function findAws() {
  AWS="aws"
  AWS_INSTALLED="no"
  if command -v aws &> /dev/null
  then
    AWS_INSTALLED="yes"
  elif doIsWindows
  then
    local aws_win
    aws_win="${PROGRAMFILES}"
    aws_win="$(cygpath "${aws_win}")"
    aws_win="${aws_win}/Amazon/AWSCLIV2/aws"
    if [ -f "${aws_win}" ]
    then
      AWS="${aws_win}"
      AWS_INSTALLED="yes"
    fi
  fi
}

# $1: path_to_package
# $2: software version
function doPackageInstall()
{
  local path_to_package="${1}"
  local version="${2}"
  if doIsWindows
  then
    doEcho "Installing AWS for Windows..."
    windows_path_to_package=$(cygpath -w "${path_to_package}")
    powershell.exe -Command "Start-Process msiexec.exe -verb runas -Wait -ArgumentList '/I ${windows_path_to_package}\aws-${version}-windows.msi /quiet'"
  elif doIsMacOs
  then
    doEcho "Installing AWS for MacOS..."
    sudo installer -pkg "${path_to_package}"/aws-"${version}"-mac.pkg -target /
  else
    doEcho "Installating AWS for Linux..."
    if [ -L "/usr/local/bin/aws" ]
    then
      doRunCommand "sudo ${path_to_package}/install -u"
    else
      doRunCommand "sudo ${path_to_package}/install"
    fi
  fi
}

function doSetup() {
  local ERR=""
  findAws
  if [[ ${AWS_INSTALLED} != "yes" ]] || [[ "${1}" != "silent" ]]
  then
    # Get leatest release
    if [ -z "${AWS_VERSION}" ]
    then
      doEcho "Getting latest release..."
      AWS_VERSION=$(curl "https://github.com/aws/aws-cli/tags" | awk -F'tags/' '/archive/ { print $2}' | sort -r | head -1 | awk -F'.zip' '{print $1}')
    fi

    doInstall "-" "${DEVON_IDE_HOME}/updates/install/aws" "aws" "${AWS_VERSION}"
    ERR="${?}"
    if [ "${ERR}" = "0" ]
    then
      doPackageInstall "${DEVON_IDE_HOME}/updates/install/aws" "${AWS_VERSION}"
    fi
    doRunCommand "rm -rf ${DEVON_IDE_HOME}/updates/install/aws"

    if [ "${1}" != "silent" ] && ! doIsQuiet
    then
      doEcho "logon again to test aws with \"aws --version\""
    fi
  fi
}


# CLI
case ${1} in
"help" | "-h")
  echo "Setup or run AWS CLI (command-line interface for Amazon-Web-Services)."
  echo
  echo "Arguments:"
  echo " setup                          install aws on your machine."
  echo " «args»                         call aws with the specified arguments. Call aws --help for details or use aws directly as preferred."
  echo
;;
"setup" | "s" | "")
  doSetup
;;
*)
  doRun "${@}"
;;
esac
