#!/usr/bin/env bash
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions

function doSetup() {
  if [ "${1}" != "silent" ] || [ ! -f "${AZ_FILE}" ] 
  then
    if [ ! -d "${PYTHON_HOME}" ] 
    then
      doDevonCommand python pip install azure-cli
      setConfig
    else
      doDevonCommand python setup silent
      doDevonCommand python pip install azure-cli
      setConfig
    fi
  fi
  if [ "${1}" != "silent" ] && ! doIsQuiet
  then
    doRunCommand "'${AZ_FILE}' -v" "verify installation of azure cli"
  fi
}
    
# Set directory for azure cli configuration file
function setConfig() {
  az_config_dir="${DEVON_IDE_HOME}/conf/.azure"
  az_config_export="export AZURE_CONFIG_DIR=${az_config_dir}"
  if ! grep -q "${az_config_export}" "${DEVON_IDE_HOME}/conf/devon.properties"
    then
      doRunCommand "${az_config_export}"
      echo -e "\n${az_config_export}" >> "${DEVON_IDE_HOME}/conf/devon.properties"
      doEcho "Location of Azure's configuration file is set to ${az_config_dir}"
  fi
}

function doRun() {
  doSetup silent
  doEcho "Running: az ${*}" 
  if doIsQuiet
  then
    "${AZ_FILE}" "${@}" > /dev/null
  else
    "${AZ_FILE}" "${@}"
  fi
}

# CLI
AZ_FILE="${DEVON_IDE_HOME}/software/python/Scripts/az"
PYTHON_HOME="${DEVON_IDE_HOME}/software/python"
case ${1} in
"help" | "-h")
  echo "Setup or run Azure CLI."
  echo
  echo "Arguments:"
  echo " setup                    setup Azure CLI (install and verify)"
  echo 
  echo
;;

"setup" | "s")
  doSetup setup
;;

*)
  doRun "${*}"
;;
esac
