#!/bin/bash
source `dirname $0`/../functions
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  echo "Run build job."
  echo "The build tool is auto-detected from according configuration files:"
  echo "  pom.xml           maven (mvnw if present, mvn otherwise)"
  echo "  build.gradle      gradle (gradlew if present, otherwise gradle)"
  echo "  package.json      npm"
  echo
  echo "Arguments:"
  echo "                    run the default build if no arguments are given. Needs to succeed for definition-of-done."
  echo "«args»              run the build with the given arguments."
  exit
fi

BUILD_CMD=
BUILD_OPTS=
if [ -f pom.xml ]
then
  if [ -x mvnw ]
  then
    BUILD_CMD="./mvnw"
  else
    BUILD_CMD="mvn"
    if which mvn > /dev/null
    then
      mkdir -p updates/releases
      mvn_version=3.6.0
      mvn_file=apache-maven-${mvn_version}-bin.tar.gz
      curl -fL http://ftp.fau.de/apache/maven/maven-3/${mvn_version}/binaries/${mvn_file} -o updates/releases ${mvn_file}
      result=${?}
      if [ "${result}" != 0 ]
      then
        echo "Failed to download ${mvn_file}"
        echo "Please check potential errors and retry."
        exit -1
      fi
      
    fi
  fi
  if [ -n "${BUILD_MVN_OPTS}" ]
  then
    BUILD_OPTS=${BUILD_MVN_OPTS}
  else
    BUILD_OPTS="clean install"
  fi
elif [ -f build.gradle ]
then
  if [ -x gradlew ]
  then
    BUILD_CMD="./gradlew"
  else
    BUILD_CMD="gradle"
  fi
  if [ -n "${BUILD_GRADLE_OPTS}" ]
  then
    BUILD_OPTS="${BUILD_GRADLE_OPTS}"
  else
    BUILD_OPTS="clean dist"
  fi
elif [ -f package.json ]
then
  BUILD_CMD="npm"
  if [ -n "${BUILD_NPM_OPTS}" ]
  then
    BUILD_OPTS="${BUILD_NPM_OPTS}"
  else
    BUILD_OPTS="build"
  fi
else
  echo "Currently not in a buildable project or build system could not be auto-detected"
  exit -1
fi

if [ -n "${1}" ]
then
  BUILD_OPTS="${@}"
fi
echo "${BUILD_CMD} ${BUILD_OPTS}"
$BUILD_CMD ${BUILD_OPTS}
