#!/usr/bin/env bash
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions

# $1: optional setup
function doSetup() {
  if command -v cicdgen &> /dev/null
  then
    if [ "${1}" != "update" ]
    then
      echo "cicdgen is already installed at $(command -v cicdgen)"
      exit
    fi
  fi

  doDevonCommand npm -q setup
  local npm_command="${DEVON_IDE_HOME}/software/node/npm"
  if [ ! -x "${npm_command}" ]
  then
    npm_command="${DEVON_IDE_HOME}/software/node/bin/npm"
  fi
  doRunCommand "'${npm_command}' install -g @devonfw/cicdgen@latest" "install cicdgen"
}

function printCicdgenHelp() {
  echo "Setup or update cicdgen CLI."
  echo
  echo "Arguments:"
  echo "setup                 setup cicdgen (install and verify)"
  echo "update                update cicdgen (reinstall with @latest version and verify)"
  echo "«args»                call cicdgen with the specified arguments"
  echo
  echo "Options:"
  exit
}

#CLI
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  printCicdgenHelp
fi

if [ -z "${1}" ] || [ "${1}" = "setup" ]
then
  doSetup setup
elif [ "${1}" = "update" ]
then
  doSetup update
else
  doSetup
  cicdgen "${@}"
fi