#!/usr/bin/env bash
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions

# $1: optional setup
function doSetup() {
  if command -v devon4node &> /dev/null
  then
    if [ "${1}" != "update" ]
    then
      echo "devon4node is already installed at $(command -v devon4node)"
      exit
    fi
  fi

  doDevonCommand npm -q setup
  local npm_command="${DEVON_IDE_HOME}/software/node/npm"
  if [ ! -x "${npm_command}" ]
  then
    npm_command="${DEVON_IDE_HOME}/software/node/bin/npm"
  fi
  doRunCommand "'${npm_command}' install -g @devon4node/devon4node@latest" "install devon4node"
}

function printDevon4nodeHelp() {
  echo "Setup or update devon4node CLI."
  echo
  echo "Arguments:"
  echo "setup                 setup devon4node (install and verify)"
  echo "update                update devon4node (reinstall with @latest version and verify)"
  echo "«args»                call devon4node with the specified arguments"
  echo
  echo "Options:"
  exit
}

#CLI
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  printDevon4nodeHelp
fi

if [ -z "${1}" ] || [ "${1}" = "setup" ]
then
  doSetup setup
elif [ "${1}" = "update" ]
then
  doSetup update
else
  doSetup
  devon4node "${@}"
fi