#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup help"
  fi
  exit
fi

if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions

# $1: optional setup
function doSetup() {  
  if [ ! "$DOCKER_EDITION" = "DOCKERDESKTOP" ]
  then
    echo "Rancher Desktop set as option"

    doIsRancherInstalled 
    echo $?
    if doIsRancherInstalled 
    then
      echo "INSIDE THE RANCHER-INSTALLED LOOP"
      if [ "${1}" != "silent" ] && ! doIsQuiet
      then
        doEcho "Rancher-Desktop is already installed at $(command -v rancher)"
        rancher version
      fi
    else
      doRequireNotBatch
  #   if doIsWindows || doIsMacOs
  #   then
  #     doDevonCommand rancher setup silent
      local version="${RANCHER_VERSION:-1.1.1}"
      local code
      #include case for windows and for mac
      #for this understand how mirrors work
      if doIsWindows
      then
        code="Rancher.Desktop.Setup."
        ############################## echo block for debugging
        echo "for windows setting code to: ${code}"
        ##############################
      elif doIsMacOs
      then
        code=""
      else
        code="rancher-desktop-linux-v"
        ############################## echo block for debugging
        echo "for linux setting code to: ${code}"
        ##############################
      fi
        ############################## echo block for debugging
        echo "starting download for rancher with version ${version} and ${code}"
        ##############################
      doDownload "-" "" "rancher" "${version}" "" "${code}"
      if doIsWindows
      then
        doEcho "Installing Rancher Desktop for Windows..."
        doRunCommand "${DEVON_DOWNLOAD_DIR}/rancher-1.1.1-windows.exe"
      elif doIsMacOs
      then
        doEcho "Installing Rancher Desktop for MacOS..."
        local mount_dir="${DEVON_IDE_HOME}/updates/volume"
        mkdir -p "${mount_dir}"
        doRunCommand "hdiutil attach -quiet -nobrowse -mountpoint '${mount_dir}' '${DEVON_DOWNLOAD_DIR}/Docker.dmg'"
        doRunCommand "cp -a '${mount_dir}'/*.app /Applications/"
        doRunCommand "hdiutil detach -force '${mount_dir}'"
      fi
      mkdir "${DEVON_IDE_HOME}"/software/rancher; touch rancher-install-info.txt; echo "Rancher Desktop installed globally" > install-info.txt
      ls "${DEVON_IDE_HOME}"/software/rancher
      read -r -p "Rancher Desktop has been installed. Please read https://github.com/devonfw/ide/blob/master/documentation/docker.asciidoc#setup for enabling kubernetes and further important details. Press enter to continue" answer
    fi



  else
  if doIsDockerInstalled 
  then
    if [ "${1}" != "silent" ] && ! doIsQuiet
    then
      doEcho "docker is already installed at $(command -v docker)"
      docker version
    fi
  else
    doRequireNotBatch
    #Start setup
      ##############################

      echo "Docker Version was set to: ${DOCKER_VERSION}"

      ##############################
    local version="${DOCKER_VERSION:-stable}"
    local code
    if doIsWindows
    then
      code="Docker%20Desktop%20Installer"
    elif doIsMacOs
    then
      code="Docker"
    else
      doFail "Sorry, docker-installation support is not yet implemented for your OS. Please install manually or help devonfw-ide to support it for your OS by contributing a pull-request."
    fi
    doDownload "-" "" "docker" "${version}" "" "${code}"
    if doIsWindows
    then
        doEcho "installing Docker Desktop for Windows..."
      doRunCommand "${DEVON_DOWNLOAD_DIR}/docker-stable-win.exe"
    elif doIsMacOs
    then
        doEcho "installing Docker Desktop for MacOS..."
      local mount_dir="${DEVON_IDE_HOME}/updates/volume"
      mkdir -p "${mount_dir}"
      doRunCommand "hdiutil attach -quiet -nobrowse -mountpoint '${mount_dir}' '${DEVON_DOWNLOAD_DIR}/Docker.dmg'"
      doRunCommand "cp -a '${mount_dir}'/*.app /Applications/"
      doRunCommand "hdiutil detach -force '${mount_dir}'"
    fi
    read -r -p "Docker Desktop has been installed. Please read https://github.com/devonfw/ide/blob/master/documentation/docker.asciidoc#setup for enabling kubernetes and further important details. Press enter to continue" answer
    fi
  fi
}


# Call Docker with specified arguments.
function doRun() {
  doSetup silent
  doEcho "Running: docker ${*}"
  docker "${@}"
}

# OS independent check if docker is installed.
function doIsDockerInstalled() {
  if command -v docker &> /dev/null
  then 
    return
  else
    return 255
  fi
}

#OS independent check if Rancher Desktop is installed.
function doIsRancherInstalled() {
    if [ -f "${DEVON_IDE_HOME}/software/rancher/rancher-install-info.txt" ]
    ###################Problem: Wenn Rancher Desktop über Windows deinstalliert wird,
    ###################so bleibt diese Testdatei 
    then 
      return
    else
      return 255
    fi
}

# CLI
case ${1} in 
"help" | "-h")
  echo "Setup docker."
  echo
  echo "Arguments:"
  echo " setup                    setup docker on your machine (global installation)."
  echo " «args»                   call docker with the specified arguments. Call docker help for details or use docker directly as preferred."
  echo
;;
"setup" | "s" | "")
  doSetup setup "${2}"
;;
*)
   doRun "${@}"
;;
esac
