#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup help"
  fi
  exit
fi

if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions

# $1: optional setup
function doSetup() {  
  if doIsDockerInstalled 
  then
    doEcho "docker is already installed at $(command -v docker)"
    docker version
  else
    doRequireNotBatch
    #Start setup
    if doIsWindows
    then
      local downloadUrl="https://desktop.docker.com/win/stable/amd64/Docker%20Desktop%20Installer.exe"
      doEcho "Downloading Docker Desktop for Windows..."
      doDownload "${downloadUrl}" "Docker_Desktop_Installer.exe"
      doEcho "Installating Docker Desktop for Windows..."
      doRunCommand "${DEVON_DOWNLOAD_DIR}/Docker_Desktop_Installer.exe"
    elif doIsMacOs
    then
      local downloadUrl
      local arch
      arch="$(uname -m)"
      if [ "${arch}" = "x86_64" ]
      then
        downloadUrl="https://desktop.docker.com/mac/stable/amd64/Docker.dmg"
      elif [ "${arch}" = "arm64" ]
      then
        downloadUrl="https://desktop.docker.com/mac/stable/arm64/Docker.dmg"
      else
        doFail "Unsupported MacOS architecture ${arch}. Please install docker manually:\nhttps://docs.docker.com/docker-for-mac/install/"
      fi
      doEcho "Downloading Docker Desktop for MacOS..."
      doDownload "${downloadUrl}" "Docker.dmg"
      doEcho "Installating Docker Desktop for MacOS..."
      local mount_dir="${DEVON_IDE_HOME}/updates/volume"
      mkdir -p "${mount_dir}"
      doRunCommand "hdiutil attach -quiet -nobrowse -mountpoint '${mount_dir}' '${DEVON_DOWNLOAD_DIR}/Docker.dmg'"
      doRunCommand "cp -a '${mount_dir}'/*.app /Applications/"
      doRunCommand "hdiutil detach -force '${mount_dir}'"
    else
      doFail "Sorry, docker-installation support is not yet implemented for your OS. Please install manually or help devonfw-ide to support it for your OS by contributing a pull-request."
    fi
    read -r -p "Docker Desktop has been installed. Please read https://github.com/devonfw/ide/blob/master/documentation/docker.asciidoc#setup for enabling kubernetes and further important details. Press enter to continue" answer
  fi
}

# Call Docker with specified arguments.
function doRun() {
  doSetup
  doEcho "Running: docker ${*}"
  docker "${@}"
}

# OS independent check if docker is installed.
function doIsDockerInstalled() {
  if command -v docker &> /dev/null
  then 
    doEcho "docker is already installed at $(command -v docker)"
  else
    return 255
  fi
}

# CLI
case ${1} in 
"help" | "-h")
  echo "Setup docker."
  echo
  echo "Arguments:"
  echo " setup                    setup docker on your machine (global installation)."
  echo " «args»                   call docker with the specified arguments. Call docker help for details or use docker directly as preferred."
  echo
;;
"setup" | "s" | "")
  doSetup setup
;;
*)
   doRun "${@}"
;;
esac
