#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  all_opts="ws-update ws-reverse ws-reverse-add create-script"
  if [ -z "${2}" ]
  then
    echo "--all setup version add-plugin run start ${all_opts} import help"
  elif [ "${2}" = "--all" ]
  then
    echo "${all_opts}"
  fi
  exit
fi

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions
ECLIPSE_HOME="${DEVON_IDE_HOME}/software/eclipse"
ECLIPSE="${ECLIPSE_HOME}/eclipse"
if doIsWindows
then
  ECLIPSE="${ECLIPSE_HOME}/eclipsec"
fi
ECLIPSE_JAVA_HOME="${JAVA_HOME}"
if [ -n "${EXTRA_JAVA_VERSION}" ]
then
  ECLIPSE_JAVA_HOME="${DEVON_IDE_HOME}/software/extra/java"
fi
ECLIPSE_PRODUCT="${ECLIPSE_HOME}/.eclipseproduct"
if doIsMacOs
then
  ECLIPSE_PRODUCT="${DEVON_IDE_HOME}/software/macos/eclipse/Eclipse.app/Contents/Eclipse/.eclipseproduct"
fi
TOOL_VERSION_COMMAND="cat '${ECLIPSE_PRODUCT}'"
# shellcheck source=scripts/commandlet-cli
source "$(dirname "${0}")"/../commandlet-cli

L_PWD=$(pwd)
cd "${DEVON_IDE_HOME}" || exit 255

function doCreateProperties() {
  #create properties file at propertiesPath with propertiesFile as name, if plugin name was not specified, use plugin_id as filename, file contents are plugin_url and plugin_id
  local propertiesPath="${DEVON_IDE_HOME}/settings/eclipse/plugins"
  local pluginId="${1}"
  local pluginUrl="${2}"
  local pluginName="${3}"
  local pluginStatus="${4}"
  if [ -z "${pluginStatus}" ]
  then
    pluginStatus="false"
  fi
  local propertiesFile="${propertiesPath}/${pluginName}.properties"
  if [ -z "${pluginName}" ]
  then
    pluginName="${pluginId}"
    propertiesFile="${propertiesPath}/${pluginId}.properties"
  fi
  if [ -f "${propertiesFile}" ]
  then
    return
  fi
  echo -e "plugin_url=${pluginUrl}\nplugin_id=${pluginId}\nplugin_active=${pluginStatus}" >>"${propertiesFile}"
}


function doInstallEclipsePlugin() {
  local doinstall_Plugin_Id="${1}"
  local doinstall_Plugin_Url="${2}" #Update site
  local doinstall_Plugin_Name="${3}" # if specified, the plugin will be installed and a properties file will be created with the name specified
  if [ -z "${doinstall_Plugin_Name}" ]
  then
    doinstall_Plugin_Name="${doinstall_Plugin_Id}"
  fi
  echo "Installing Eclipse plugin '${doinstall_Plugin_Name}' from URL ${doinstall_Plugin_Url}..."

  local plugin_dependencies
  plugin_dependencies=$(doCheckPluginsInstalled "${doinstall_Plugin_Id}")

  # Install plugins and write debug info into temp file
  local debug_info_file
  debug_info_file=$(mktemp)
  # get only !MESSAGE lines from the debug inf

  "${ECLIPSE}" -consoleLog -nosplash -vm "${ECLIPSE_JAVA_HOME}/bin/java" -application org.eclipse.equinox.p2.director -repository "${doinstall_Plugin_Url}" -installIU "${doinstall_Plugin_Id}" -vmargs "${ECLIPSE_VMARGS}" | grep '^!MESSAGE' | sed 's/^!MESSAGE //' >"${debug_info_file}" 2>&1
  local exit_code=$?
  if [[ $(grep "Overall install request is satisfiable" "${debug_info_file}") != "" ]] && [ "${exit_code}" == 0 ]
  then
    #If plugin name was specified, create a properties file for an easier remove plugin process.

    return 0
  elif [[ $(grep "Unable to load repositories" "${debug_info_file}") != "" ]] || [[ $(grep "No repository found at" "${debug_info_file}") != "" ]]
  then
    doError "The given repository ${doinstall_Plugin_Url} is not a correct update site."
    return 1
  else
    echo
    doError "Installation of plugin '${doinstall_Plugin_Name}' failed: \n$(cat "${debug_info_file}")"
    if [ -n "${plugin_dependencies}" ]
    then
      plugin_dependencies=$(echo -e "${plugin_dependencies}" | sort -u)
      doWarning "Plugin '${doinstall_Plugin_Name}' might be already installed, because of existing dependencies: ${plugin_dependencies} \nMake sure the plugin is not installed yet by checking the list of installed plugins in the Eclipse IDE. If there's an error and the issue persists, try to remove the plugin manually from the plugins folder or uninstall it with devon remove-plugin command."
    fi
    return 1
  fi
}

# Check if the plugins are already installed by looking at the eclipse/plugins folder
# $1: plugin feature group ID
# return: dependencies that are already installed
function doCheckPluginsInstalled() {
  local plugin_dir="${DEVON_IDE_HOME}/software/eclipse/plugins"

  # Remove feature.group from each plugin id
  local plugins="${1//.feature.group/}"
  # Remove spaces from plugin variable
  plugins="${1// /}"
  # Iterate each plugin via comma seperation
  IFS=',' read -ra plugins_arr <<<"${plugins}"
  for plugin in "${plugins_arr[@]}"
  do
    # Remove feature from plugin variable
    plugin=${plugin/\.feature*/}

    local plugin_dependencies
    plugin_dependencies=$(ls -1 "${plugin_dir}"/*"${plugin}".* 2>/dev/null)
    # Remove last word after dot
    while [[ "${plugin}" == *.* ]]; do
      if [ "${plugin}" == "org.eclipse" ] || [ "${plugin}" == "org.apache" ] || [ "${plugin}" == "com" ] || [ "${plugin}" == "org" ] || [ "${plugin}" == "net" ]
      then
        break
      fi

      local new_plugin_dependencies
      new_plugin_dependencies=$(ls -1 "${plugin_dir}"/*"${plugin}".* 2>/dev/null)
      if [ -n "${new_plugin_dependencies}" ]
      then
        plugin_dependencies="${plugin_dependencies}\n${new_plugin_dependencies}"
      fi
      plugin=${plugin%.*}
    done
  done
  # Remove plugin_dir from plugin variable
  plugin_dependencies=$(echo -e "${plugin_dependencies}" | sed "s|${plugin_dir}/||g")
  echo -e "${plugin_dependencies}" | sort -u
}

# Remove plugins from Eclipse by feature group ID
function doRemovePlugin() {
  local rm_plugin_id="${1}"
  if [ -z "${rm_plugin_id}" ]
  then
    doError "No plugin was specified for removal."
    return 1
  fi
  doLoadPluginProperties "${rm_plugin_id}"
  if [ -z "${plugin_id}" ]
   then
    #if $1 contains dots, we can be quite sure that it is a viable plugin_id, 
    if [[ "${rm_plugin_id}" == *.* ]]
    then
      plugin_id="${rm_plugin_id}"
    else
      doError "Plugin ${rm_plugin_id} is not installed.\nMake sure you provided the correct plugin.properties name or plugin id."
    fi
  fi
    doEcho "Removing plugin ${plugin_id}..."
    local debug_info_file
    debug_info_file=$(mktemp)
    "${ECLIPSE}" -nosplash -clean -consoleLog -vm "${ECLIPSE_JAVA_HOME}/bin/java" -application org.eclipse.equinox.p2.director -uninstallIU "${plugin_id}" -vmargs "${ECLIPSE_VMARGS}" >"${debug_info_file}" 2>&1
    local exit_code=$?
    # Overwrite file with lines containing !MESSAGE
    sed -i -n '/!MESSAGE/ p' "${debug_info_file}"

    plugin_dependencies=$(doCheckPluginsInstalled "${plugin_id}")
    plugin_id="${plugin_id// /}"
    IFS=',' read -ra plugin_id_arr <<<"${plugin_id}"
    for plugin in "${plugin_id_arr[@]}"; do
      # If debug info contains words The installable unit could not be found, then the plugin was not uninstalled correctly
      if [[ $(grep "The installable unit ${plugin} has not been found" "${debug_info_file}") != "" ]]
       then
        doError "Plugin ${plugin} couldn't be removed from your Eclipse installation as it was not found. Please check if the plugin exists and try to remove it manually."
        if [ -n "${plugin_dependencies}" ]
        then
          doWarning "If the problem persists, try removing the following dependencies: ${plugin_dependencies}"
        fi
        return 1
      fi
    done
    doSuccess "Plugin ${plugin_id} removed successfully."
  
}

function doSetup() {
  local silent="${1}"
  doDevonCommand java setup silent
  # check version
  local javaVersion="${EXTRA_JAVA_VERSION}"
  if [ -z "${javaVersion}" ]
  then
    javaVersion="${JAVA_VERSION}"
  fi
  if [ -n "${javaVersion}" ]
  then
    doVersionCompare "${javaVersion}" "11u0"
    if [ "${?}" == 2 ]
    then
      # Java version is lower than 11
      local requireJava11="no"
      if [ -z "${ECLIPSE_VERSION}" ]
      then
        requireJava11="yes"
      else
        doVersionCompare "${ECLIPSE_VERSION}" "2020-09"
        if [ "${?}" != 2 ]
        then
          # Eclipse version is >= 2020-09
          requireJava11="yes"
        fi
      fi
      if [ "${requireJava11}" = "yes" ]
      then
        doConfirmWarning "You are using eclipse version ${ECLIPSE_VERSION:-latest} that requires Java 11 or newer.\nHowever, [EXTRA_]JAVA_VERSION is ${javaVersion} - in this setup eclipse can not work.\nPlease update JAVA_VERSION, set EXTRA_JAVA_VERSION or downgrade ECLIPSE_VERSION in your settings/devon.properties!"
      fi
    fi
  fi
  doInstall "eclipse" "${ECLIPSE_VERSION}" "${silent}" "${ECLIPSE_EDITION_TYPE:-java}"
  if [ "${?}" = 0 ]
  then
    doAddPlugins
  fi
}

# $1: plugin config properties file
function doAddPluginFromConfig() {
  local plugin_properties_file="${1}"
  local optional_Plugin_Active="${2}"
  local url=""
  if [ -f "${plugin_properties_file}" ]
  then
    doLoadPluginProperties "${plugin_properties_file}"
    if [ -n "${plugin_mirror_url}" ]
    then
      url="${plugin_mirror_url}"
    else
      url="${plugin_url}"
    fi
    if [ -n "${plugin_id}" ] && [ -n "${url}" ] && [ "$plugin_active" = "true" ] || [ "${optional_Plugin_Active}" = "true" ] 
    then
      doInstallEclipsePlugin "${plugin_id}" "${url}" "$(basename "${plugin_properties_file%.*}")"
    fi
  else 
    doError "Plugin ${plugin_properties_file} was not found.\nMake sure you provided the correct plugin.properties name."
  fi

}

function doAddPlugins() {
  if [ -d "${SETTINGS_PATH}"/eclipse/plugins ]
  then
    local file
    for file in "${SETTINGS_PATH}"/eclipse/plugins/*.properties; do
      doAddPluginFromConfig "${file}"
    done
  else
    doWarning "Legacy eclipse plugin mechanism detected. Please migrate to ${SETTINGS_PATH}/eclipse/plugins:\nhttps://github.com/devonfw/ide/blob/master/documentation/eclipse.asciidoc"
    if [ -z "${ECLIPSE_PLUGINS}" ]
    then
      doAddPlugin startexplorer
      doAddPlugin regexutil
      doAddPlugin templatevariables
      doAddPlugin spotbugs
      doAddPlugin checkstyle
      doAddPlugin cobigen
      doAddPlugin terminal
    else
      for ((i = 0; i < ${#ECLIPSE_PLUGINS[*]}; i = i + 2)); do
        doAddPlugin "${ECLIPSE_PLUGINS[${i}]}" "${ECLIPSE_PLUGINS[((${i} + 1))]}"
      done
    fi
  fi
}

function doConfigureEclipse() {
  local mode="${1}"
  if [ ! -d "${WORKSPACE_PATH}/.metadata" ]
  then
    if [ -z "${mode}" ]
    then
      mode="-u"
    elif [ "${mode}" != "-u" ]
    then
      doFail "Workspace ${WORKSPACE} is not initialized.\nReverse merge is not possible."
    fi
  fi
  if [ -n "${mode}" ]
  then
    doConfigureWorkspace "${SETTINGS_PATH}/eclipse/workspace" "${WORKSPACE_PATH}" ${mode}
  fi
}


function doAddPlugin() {
  local doadd_Plugin_Id="${1}"
  local doadd_Plugin_Url="${2}"
  local doadd_Plugin_Name="${3}" #optional
  if [ -z "${doadd_Plugin_Url}" ] 
  then
    doAddPluginFromConfig "${SETTINGS_PATH}/eclipse/plugins/${doadd_Plugin_Id}.properties" "true"
    if [ ! "${?}" = 0 ]
    then
      doError "There was an error during the installation. Please try to call add-plugin again with parameters: «id» [«url»] «plugin name»[optional]."
    fi
  else
    doInstallEclipsePlugin "${doadd_Plugin_Id}" "${doadd_Plugin_Url}" "${doadd_Plugin_Name}"
    if [ "${?}" = 0 ] && [ -n "${doadd_Plugin_Name}" ]
      then
      doCreateProperties "${doinstall_Plugin_Id}" "${doinstall_Plugin_Url}" "${doinstall_Plugin_Name}"
    fi
  fi
}

function doStartEclipse() {
  doConfigureEclipse -u
  echo "launching Eclipse in workspace ${WORKSPACE} at ${WORKSPACE_PATH}"
  if doIsWindows
  then
    # shellcheck disable=SC2086
    start "eclipse" /B "${ECLIPSE}" -clean -data "${WORKSPACE_PATH}" -keyring ~/.eclipse/.keyring -vm "${ECLIPSE_JAVA_HOME}/bin/javaw" -showlocation "${WORKSPACE}" -vmargs ${ECLIPSE_VMARGS}
  else
    # shellcheck disable=SC2086
    "${ECLIPSE}" -clean -data "${WORKSPACE_PATH}" -keyring ~/.eclipse/.keyring -vm "${ECLIPSE_JAVA_HOME}/bin/java" -showlocation "${DEVON_IDE_HOME/*\//}/${WORKSPACE}" -vmargs ${ECLIPSE_VMARGS} &
  fi
}

function doCheckAndInstallGroovy() {
  local groovy_version=3.0.1
  if [ ! -f "${M2_REPO}/org/codehaus/groovy/groovy-ant/${groovy_version}/groovy-ant-${groovy_version}.jar" ] || [ ! -f "${M2_REPO}/org/codehaus/groovy/groovy/${groovy_version}/groovy-${groovy_version}.jar" ]
  then
    echo "Groovy not found. Installing version ${groovy_version} in Maven repository ${M2_REPO}..."
    doRunCommand "mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:get -Dartifact=org.codehaus.groovy:groovy-ant:${groovy_version}:jar -DremoteRepositories=https://mvnrepository.com"
  fi
}

function doImportEclipse() {
  if [ -z "${1}" ]
  then
    doFail "Parameter \"path\" is missing."
  fi
  doConfigureEclipse
  doCheckAndInstallGroovy
  if [[ "${1}" = /* ]]
  then
    importPath="${1}"
  else
    # Path is relative make it absolute
    importPath="${L_PWD}/${1}"
  fi
  importWorkingSets="${2}"
  echo "Starting eclipse import for ${importPath} into workspace ${WORKSPACE} at ${WORKSPACE_PATH}"
  # shellcheck disable=SC2086
  "${ECLIPSE}" -nosplash -vm "${ECLIPSE_JAVA_HOME}/bin/java" -application org.eclipse.ant.core.antRunner -buildfile "${DEVON_IDE_HOME}/scripts/lib_script/import.xml" -data "${WORKSPACE_PATH}" -keyring ~/.eclipse/.keyring -vm "${ECLIPSE_JAVA_HOME}/bin/java" -vmargs -DdevonImportPath="${importPath}" -DdevonImportWorkingSet="${importWorkingSets}" ${ECLIPSE_VMARGS}
}

# $1: id
# $2: optional plugin URL (update site)
function doMirrorUpdateSite() {
  local domirror_Plugin_Id="${1}"
  local domirror_Plugin_Url="${2}" #optional Update Site
  if [ -z "${domirror_Plugin_Id}" ]
  then
    doFail "Parameter \"id\" is missing."
  fi
  local url
  if [ -n "${domirror_Plugin_Url}" ]
  then
    url="${domirror_Plugin_Url}"
  else
    doLoadPluginProperties "${domirror_Plugin_Id}"
    url="${plugin_url}"
  fi
  local timestamp
  timestamp=$(date +'%Y-%m-%d')
  "${ECLIPSE}" -nosplash -vm "${ECLIPSE_JAVA_HOME}/bin/java" -application org.eclipse.equinox.p2.metadata.repository.mirrorApplication -source "${url}" -destination "${DEVON_DOWNLOAD_DIR}/update-sites/${domirror_Plugin_Id}-${timestamp}" -vmargs "${ECLIPSE_VMARGS}"
  "${ECLIPSE}" -nosplash -vm "${ECLIPSE_JAVA_HOME}/bin/java" -application org.eclipse.equinox.p2.artifact.repository.mirrorApplication -source "${url}" -destination "${DEVON_DOWNLOAD_DIR}/update-sites/${domirror_Plugin_Id}-${timestamp}" -vmargs "${ECLIPSE_VMARGS}"
  local result="${?}"
  if [ "${result}" != 0 ]
  then
    doEchoAttention "Mirroring of the update-site ${url} failed. Please check the URL or rerun setup (devon eclipse setup)."
  fi
  return "${result}"
}

function doLoadPluginProperties() {
  local file="${1}"
  if [ ! -f "${1}" ]
  then
    file="${SETTINGS_PATH}/eclipse/plugins/${1}.properties"
  fi
  if [ -f "${file}" ] 
  then
    plugin_id=""
    plugin_active=""
    plugin_url=""
    plugin_mirror_url=""
    doLoadProperties "${file}"
    if [ -z "${plugin_id}" ] || [ -z "${plugin_url}" ]
    then
      doFail "Invalid eclipse plugin config: ${file}"
    fi
  fi
}

# CLI
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  echo "Manage Eclipse IDE and workspace."
  echo
  echo "Arguments:"
  echo " --all                          if provided as first arg then to command will be invoked for each workspace"
  echo " setup                          setup Eclipse (install or update)"
  echo " add-plugin «id» [«url»] «plugin name» [optional, creates properties file with given name]        install an additional plugin"
  echo " remove-plugin «id»[or .properties filename, if exists]             remove an installed plugin with given id"
  echo " run | start                    launch Eclipse IDE (default if no argument is given)"
  echo " ws-up[date]                    update eclipse workspace"
  echo " ws-re[verse]                   reverse merge changes from workspace into settings"
  echo " ws-reverse-add                 reverse merge adding new properties"
  echo " create-script                  create eclipse-${WORKSPACE} script if not already exists"
  echo " import «path» [«workingsets»]  import projects in «path» into current workspace. «workingsets» comma-separated list of workingsets (no spaces between ,), eg: ./myproject ws1,ws2"
  echo " mirror «id» [«url»]            mirror the content of an update-site"
  exit
fi
if [ -z "${1}" ]
then
  doSetup silent
  doStartEclipse
elif [ "${1}" = "setup" ]
then
  doSetup "${2}"
  exit
fi
if [ "${1}" = "--all" ]
then
  shift
  doDevonCommandAllWorkspaces eclipse "${@}"
fi
while [ -n "${1}" ]; do
  if [ "${1}" = "run" ] || [ "${1}" = "start" ]
  then
    doSetup silent
    doStartEclipse
  elif [ "${1}" = "ws-up" ] || [ "${1}" = "ws-update" ]
  then
    doConfigureEclipse -u
  elif [ "${1}" = "ws-re" ] || [ "${1}" = "ws-reverse" ]
  then
    doConfigureEclipse -i
  elif [ "${1}" = "ws-reverse-add" ]
  then
    doConfigureEclipse -x
  elif [ "${1}" = "create-script" ]
  then
    doCreateIdeScript eclipse
  elif [ "${1}" = "add-plugin" ]
  then
    shift
    doAddPlugin "${@}"
    exit ${?}
  elif [ "${1}" = "remove-plugin" ]
  then
    shift
    doRemovePlugin "${@}"
    exit ${?}
  elif [ "${1}" = "import" ]
  then
    doImportEclipse "${2}" "${3}"
    exit ${?}
  elif [ "${1}" = "mirror" ]
  then
    shift
    doMirrorUpdateSite "${@}"
    exit ${?}
  else
    doFail "Unknown argument: ${1}"
  fi
  shift
done
