#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup start help"
  fi
  exit
fi

if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions

GCVIEWER_HOME="${DEVON_IDE_HOME}/software/gcviewer/"

# gcviewer installation
function doSetup(){

  local GCVIEWER_VERSION="${1}"

  if [ ! -z "${GCVIEWER_VERSION}" ]
  then
    doEcho "Getting GCviewer in version ${GCVIEWER_VERSION}..."
    doDownload "-" "${GCVIEWER_HOME}" "gcviewer" "${GCVIEWER_VERSION}"
  else
    doEcho "Getting the latest release of GCViewer..."
    GCVIEWER_VERSION=$(curl "https://github.com/chewiebug/GCViewer/tags" | awk -F "/tag/" '/GCViewer/ {print $2}' | sort -r | head -1 | awk -F "\">" '{print $1}')
    doDownload "-" "${GCVIEWER_HOME}" "gcviewer" "${GCVIEWER_VERSION}"
  fi

  if doIsMacOs
  then
    cd ${GCVIEWER_HOME}
    rm -r GCViewer.app
    doRunCommand "unzip ${GCVIEWER_HOME}gcviewer-${GCVIEWER_VERSION}-mac.zip"
  fi

  doSuccess "GCViewer has been installed successfully!"
}

function doStart(){

  if doIsWindows
  then
    if [ ! -d "${GCVIEWER_HOME}" ] || [ compgen -G "${GCVIEWER_HOME}/gcviewer*.jar" > /dev/null! ]
    then
      doSetup
    else
      doEcho "Checking if Java is installed..."
      doDevonCommand "java"
      cd ${GCVIEWER_HOME}
      doEcho "Starting GCViewer..."
      local gcviewer_jar_file=$(ls -t | head -1)
      doRunCommand "java -jar ${gcviewer_jar_file}&"
    fi
  elif doIsMacOs
  then
    if [ ! -d "${GCVIEWER_HOME}" ] || [ compgen -G "${GCVIEWER_HOME}GCViewer.app/Contents/Java/gcviewer*.jar" > /dev/null! ]
    then
      doSetup
    else
      doEcho "Checking if Java is installed..."
      doDevonCommand "java"
      cd ${GCVIEWER_HOME}GCViewer.app/Contents/Java/
      doEcho "Starting GCViewer..."
      local gcviewer_jar_file=$(ls -t | head -1)
      doRunCommand "java -jar ${gcviewer_jar_file}&"
    fi
  else
    if [ ! -d "${GCVIEWER_HOME}" ] || [ compgen -G "${GCVIEWER_HOME}gcviewer*.jar" > /dev/null! ]
    then
      doSetup
    else
      doEcho "Checking if Java is installed..."
      doDevonCommand "java"
      cd ${GCVIEWER_HOME}
      doEcho "Starting GCViewer..."
      local gcviewer_jar_file=$(ls -t | head -1)
      doRunCommand "java -jar ${gcviewer_jar_file}&"
    fi
  fi

}


# CLI
case ${1} in 
"help" | "-h")
  echo "Setup or run gcviewer"
  echo
  echo "Arguments:"
  echo " setup                    setup the latest version gcviewer on your machine."
  echo " setup <version>          setup the gcviewer specified version on your machine."
  echo " start                    start gcviewer UI."
  echo
;;
"setup" | "s")
  doSetup ${2}
;;
"start" | "")
  doStart
;;
*)
  doError "Unkown command. Call `devon gcviewer` to setup or start GCViewer OR devon gcviewer help for available commands"
;;
esac