#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version help"
  fi
  exit
fi

if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
TOOL_VERSION_COMMAND="gh --version"
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions

GH_HOME="${DEVON_IDE_HOME}/software/gh"

function doSetup(){
  # Install GitHub CLI in the software folder

  if [ ! -d "${GH_HOME}" ] || [ "${1}" != "silent" ]
  then
    doInstall "-" "${GH_HOME}" "gh" "${GH_VERSION}"
  fi

  if [ "${1}" != "silent" ] && ! doIsQuiet
  then
    doRunCommand "${TOOL_VERSION_COMMAND}"
  fi
}

function doRun(){
  doSetup silent
  doRunCommand "${GH_HOME}/bin/gh ${*}"
}

case ${1} in
"help" | "-h")
  echo "Install Github CLI."
  echo
  echo "Arguments:"
  echo " setup                          install GitHub CLI on your machine."
  echo " «args»                         call GitHub CLI with the specified arguments."
;;
"setup" | "s")
  doEcho "Installing GitHub CLI..."
  doSetup "${2}"
;;
*)
  doRun "${@}"
;;
esac