#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup help"
  fi
  exit
fi

if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions

# $1: optional setup
function doSetup() {
  GRAALVM_HOME="${DEVON_IDE_HOME}/software/extra/graalvm"
  doDevonCommand java setup silent
  if [ ! -d "${GRAALVM_HOME}" ]
  then
    local version="${GRAAL_VERSION:-22.0.0.2}"
    local javaVersion="${EXTRA_JAVA_VERSION}"
    if [ -z "${javaVersion}" ]
    then
      javaVersion="${JAVA_VERSION}"
    fi
    if [ -n "${javaVersion}" ]
    then
      doVersionCompare "${javaVersion}" "11u0"
      if [ "${?}" == 2 ]
      then
        # Java version is lower than 11
        doConfirmWarning "GraalVM requires Java 11 or newer.\nHowever, [EXTRA_]JAVA_VERSION is ${javaVersion} - in this setup GraalVM can not work.\nPlease update JAVA_VERSION or set EXTRA_JAVA_VERSION in your settings/devon.properties!"
      fi
    fi
    doInstall "-" "${GRAALVM_HOME}" "graalvm" "${version}"
  fi
  if doIsMacOs
  then
    GRAALVM_HOME="${DEVON_IDE_HOME}/software/extra/graalvm/Contents/Home"
  fi
  if [ "${1}" != "silent" ] && ! doIsQuiet
  then
    doRunCommand "'${GRAALVM_HOME}/bin/java' -version" "verify installation of GraalVM"
  fi
  export GRAALVM_HOME
}

# Call GraalVM with specified arguments
function doRun() {
  doSetup silent
  command="${GRAALVM_HOME}/bin/$*"
  if [ -f "$( echo "$command" | cut -d ' ' -f1 )" ]
  then
    ${command}
  else
    doFail "Command not found"
  fi
}

# CLI
case ${1} in 
"help" | "-h")
  echo "Setup GraalVM."
  echo
  echo "Arguments:"
  echo " setup                    setup GraalVM (install and verify)"
  echo " «args»                   call GraalVM with the specified arguments"
  echo  
;;
"setup" | "s" | "")
  doSetup "${2}"
;;
*)
  doRun "${@}"
;;
esac