#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version help"
  fi
  exit
fi

if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
GRAALVM_HOME="${DEVON_IDE_HOME}/software/extra/graalvm"
TOOL_VERSION_COMMAND="'${GRAALVM_HOME}/bin/java' -version"
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions

# $1: optional setup
function doSetup() {

  doDevonCommand java setup silent
  if [ "${1}" != "silent" ] || [ ! -d "${GRAALVM_HOME}" ]
  then
    local javaVersion="${EXTRA_JAVA_VERSION}"
    if [ -z "${javaVersion}" ]
    then
      javaVersion="${JAVA_VERSION}"
    fi
    if [ -n "${javaVersion}" ]
    then
      doVersionCompare "${javaVersion}" "11u0"
      if [ "${?}" == 2 ]
      then
        # Java version is lower than 11
        doConfirmWarning "GraalVM requires Java 11 or newer.\nHowever, [EXTRA_]JAVA_VERSION is ${javaVersion} - in this setup GraalVM can not work.\nPlease update JAVA_VERSION or set EXTRA_JAVA_VERSION in your settings/devon.properties!"
      fi
    fi
    doInstall "-" "${GRAALVM_HOME}" "graalvm" "${GRAALVM_VERSION}"

    graalvm_export="export GRAALVM_HOME=${GRAALVM_HOME}"
    if ! grep -q "${graalvm_export}" "${DEVON_IDE_HOME}/conf/devon.properties"
    then
      echo -e "\n${graalvm_export}" >> "${DEVON_IDE_HOME}/conf/devon.properties"
    fi
  fi

  if [ "${1}" != "silent" ] && ! doIsQuiet
  then
    local java_binary="${GRAALVM_HOME}/bin/java"
    if [ ! -f "${java_binary}" ]
    then
      java_binary="${GRAALVM_HOME}/bin/java.exe"
    fi
    doRunCommand "'${java_binary}' -version" "verify installation of GraalVM"
  fi
}

# Call GraalVM with specified arguments
function doRun() {
  doSetup silent
  local binary="${GRAALVM_HOME}/bin/${1}"
  shift
  if [ ! -x "${binary}" ]
  then
    if [ -f "${binary}.exe" ]
    then
      binary=${binary}".exe"
    fi
    if [ -f "${binary}.cmd" ]
    then
      binary=${binary}".cmd"
    fi
  fi

  doRunCommand "${binary} ${*}"
}

# CLI
case ${1} in 
"help" | "-h")
  echo "Setup GraalVM."
  echo
  echo "Arguments:"
  echo " setup                          setup GraalVM (install and verify)"
  echo " «args»                         call GraalVM with the specified arguments"
;;
"setup" | "s" | "")
  doSetup "${2}"
;;
*)
  doRun "${@}"
;;
esac