#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version help"
  fi
  exit
fi

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions
HELM_HOME="${DEVON_IDE_HOME}/software/helm"
TOOL_VERSION_COMMAND="helm version"
# shellcheck source=scripts/commandlet-cli
source "$(dirname "${0}")"/../commandlet-cli

# Call helm with specified arguments.
function doRun() {
  doSetup silent
  doRunCommand "${HELM_HOME}/helm ${*}"
}

function doSetup() {
  doInstall "helm" "${HELM_VERSION}" "${1}"
  return 0

}

# CLI
case ${1} in 
"help" | "-h")
  echo "Install helm."
  echo
  echo "Arguments:"
  echo " setup                          install helm on your machine."
  echo " «args»                         call helm with the specified arguments. Call helm --help for details or use helm directly as preferred."
;;
"setup" | "s" | "")
  doSetup "${2}"
;;
*)
  doRun "${@}"
;;
esac
