#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version help"
  fi
  exit
fi

if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
TOOL_VERSION_COMMAND="helm version"
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions

# Call helm with specified arguments.
function doRun() {
  doSetup silent
  doRunCommand "${HELM_HOME}/helm ${*}"
}

function doSetup() {
  if [ ! -d "${HELM_HOME}" ] || [ "${1}" != "silent" ]
  then
    doInstall "-" "${HELM_HOME}" "helm" "${HELM_VERSION}"
  fi

  if [ "${1}" != "silent" ] && ! doIsQuiet
  then
    doRunCommand "${TOOL_VERSION_COMMAND}"
  fi 

}

HELM_HOME="${DEVON_IDE_HOME}/software/helm"

# CLI
case ${1} in 
"help" | "-h")
  echo "Install helm."
  echo
  echo "Arguments:"
  echo " setup                          install helm on your machine."
  echo " «args»                         call helm with the specified arguments. Call helm --help for details or use helm directly as preferred."
;;
"setup" | "s" | "")
  doEcho "Installating helm..."
  doSetup
;;
*)
  doRun "${@}"
;;
esac
