#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    \ls "$(dirname "${BASH_SOURCE:-$0}")"/
  fi
  exit
fi

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions
TOOL_VERSION_COMMAND=
# shellcheck source=scripts/commandlet-cli
source "$(dirname "${0}")"/../commandlet-cli
echo
doLogo
echo
# shellcheck disable=SC2007,SC2154
doSuccess "Current version of devon-scripts is $[devon_ide_version]"
echo
echo $@
if [ -z "${1}" ]
then
  echo "usage: devon [command [args]]"
  echo "Setup devonfw IDE environment and optionally launch commands."
  echo 
  echo "Commands:"
  for command in "${DEVON_IDE_HOME}/scripts/command/"*
  do
    doEchoOption " $(basename "${command}")"
  done
  echo
  echo "For further details use:"
  echo "devon help <command>"
else
  echo "usage: devon ${1} [options] [args]"
  echo
  if [ "${1}" = "help" ]
  then
    echo "devon help <command>"
    echo "Print help for <command>"
  else
    doDevonCommand "${1}" help
    if [ -f "${DEVON_IDE_HOME}/ide-mirrors/${1}/available-versions" ]
    then
      echo " version list | set [«v»]       list available versions or set a specific version «v»."
    fi
    echo
    echo "Options:"
    echo " -b | --batch         run in non-interactive mode (do not ask any questions)."
    echo " -q | --quiet         be quiet and avoid output."
    echo " -d | --debug         be extra verbose and print more output for debugging."
    echo " -f | --force         force proceeding even in case of warnings."
  fi
fi
