#!/usr/bin/env bash
source "$(dirname "${0}")"/../functions
cd "${DEVON_IDE_HOME}"

function doSetup() {
  if [ -d "${IDEA_HOME}" ]
  then
    if [ -n "${1}" ]
    then
      echo "IntelliJ is already installed at ${IDEA_HOME}"
    fi
  else
    #mirror="https://mirror.math.princeton.edu"
    mirror="https://ftp.osuosl.org"
    software_version="${INTELLIJ_VERSION:-2018.3.5}"
    eclipse_edition=java
    #eclipse_edition=jee
    if doIsMacOs
    then
      software_type="dmg"
    elif doIsWindows
    then
      software_type="win.zip"
    else
      software_type="tar.gz"
    fi
    download_url="https://download-cf.jetbrains.com/idea/ideaIC-${software_version}.${software_type}"
    doInstall "${IDEA_HOME}" "${download_url}" "" "intellij"
    if doIsMacOs
    then
      echo "Doing workarounds for MacOS quirks..."
      mv "${DEVON_IDE_HOME}/software/intellij/IntelliJ IDEA CE.app" "${DEVON_IDE_HOME}/software/intellij/IntelliJ.app"
      echo -e "#!/usr/bin/env bash\n'${DEVON_IDE_HOME}/software/intellij/IntelliJ.app/Contents/MacOS/idea' \$@" > "${IDEA_HOME}/idea"
      chmod a+x "${IDEA_HOME}/idea"
    fi
  fi
  if [ -n "${1}" ]
  then
    doRunCommand "command -v idea" "verify installation of IntelliJ"
    if [ -e "${IDEA_HOME}/product-info.json" ]
    then
      doRunCommand "cat '${IDEA_HOME}/product-info.json'"
    else
      doRunCommand "cat '${IDEA_HOME}/IntelliJ.app/Contents/Resources/product-info.json'"
    fi
  fi
}

function doConfigureIntellij() {
  local mode="${1}"
  if [ ! -d "${WORKSPACE_PATH}/.idea" ]
  then
    if [ -z "${mode}" ]
    then
      mode="-u"
    elif [ "${mode}" != "-u" ]
    then
      doFail "Workspace ${WORKSPACE} is not initialized.\nReverse merge is not possible."
    fi
  fi
  if [ -n "${mode}" ]
  then
    doConfigureWorkspace "${SETTINGS_PATH}/intellij/workspace" "${WORKSPACE_PATH}" ${mode}
  fi
}

function doStartIntellij() {
  doConfigureIntellij
  echo "launching IntelliJ..."
  "${IDEA_HOME}/idea" &
}

# CLI
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  echo "Manage IntelliJ IDE and workspace."
  echo
  echo "Arguments:"
  echo " setup              setup IntelliJ (install and verify)"
  echo " run | start        launch IntelliJ IDE (default if no argument is given)"
  echo " ws-up[date]        update IntelliJ workspace"
  echo " ws-re[verse]       reverse merge changes from workspace into settings"
  echo " ws-reverse-add     reverse merge adding new properties"
  echo " create-script      create intellij-${WORKSPACE} script if not already exists"
  exit
fi
IDEA_HOME="${DEVON_IDE_HOME}/software/intellij"
if [ -z "${1}" ]
then
  doSetup
  doStartIntellij
fi
while [ -n "${1}" ]
do
  if [ "${1}" = "run" ] || [ "${1}" = "start" ]
  then
    doStartIntellij
  elif [ "${1}" = "ws-up" ] || [ "${1}" = "ws-update" ]
  then
    doConfigureEclipse -u
  elif [ "${1}" = "ws-re" ] || [ "${1}" = "ws-reverse" ]
  then
    doConfigureEclipse -i
  elif [ "${1}" = "ws-reverse-add" ]
  then
    doConfigureEclipse -x
  elif [ "${1}" = "setup" ]
  then
    doSetup setup
    doCreateIdeScript intellij
  elif [ "${1}" = "create-script" ]
  then
    doCreateIdeScript intellij
  else
    doFail "Unknown argument: ${1}"
  fi
  shift
done
