#!/usr/bin/env bash
if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions
cd "${DEVON_IDE_HOME}" || exit 255

function doSetup() {
  doDevonCommand java -q setup
  if [ -n "${1}" ] || [ ! -d "${IDEA_HOME}" ]
  then
    software_version="${INTELLIJ_VERSION:-2020.2.1}"
    software_edition_type="${INTELLIJ_EDITION_TYPE:-C}"
    if doIsMacOs
    then
      software_type="dmg"
    elif doIsWindows
    then
      software_type="win.zip"
    else
      software_type="tar.gz"
    fi
    #mirror="https://mirror.math.princeton.edu"
    #mirror="https://ftp.osuosl.org"
    download_url="https://download-cf.jetbrains.com/idea/ideaI${software_edition_type}-${software_version}.${software_type}"
    doInstall "${IDEA_HOME}" "${download_url}" "intellij" "${software_version}-${software_edition_type}"
    if [ "${?}" = 0 ] && doIsMacOs
    then
      echo "Doing workarounds for MacOS quirks..."
      if [ "${software_edition_type}" = "U"  ]
      then
        mv "${DEVON_IDE_HOME}/software/intellij/IntelliJ IDEA.app" "${DEVON_IDE_HOME}/software/intellij/IntelliJ.app"
      else
        mv "${DEVON_IDE_HOME}/software/intellij/IntelliJ IDEA CE.app" "${DEVON_IDE_HOME}/software/intellij/IntelliJ.app"
      fi
      mkdir -p "${IDEA_HOME}/bin"
      echo -e "#!/usr/bin/env bash\n'${DEVON_IDE_HOME}/software/intellij/IntelliJ.app/Contents/MacOS/idea' \$@" > "${IDEA_HOME}/bin/idea"
      chmod a+x "${IDEA_HOME}/bin/idea"
    fi
    if  [ -f "${IDEA_HOME}/bin/idea.sh" ]
    then
       ln -s "${IDEA_HOME}/bin/idea.sh" "${IDEA_HOME}/bin/idea"
    fi
    export PATH="${IDEA_HOME}/bin:${PATH}"
  fi
  if [ -n "${1}" ]
  then
    doRunCommand "command -v idea" "verify installation of IntelliJ"
    if [ -e "${IDEA_HOME}/product-info.json" ]
    then
      doRunCommand "cat '${IDEA_HOME}/product-info.json'"
    else
      doRunCommand "cat '${IDEA_HOME}/IntelliJ.app/Contents/Resources/product-info.json'"
    fi
  fi
}

function doConfigureIntellij() {
  local mode="${1}"
  if [ ! -d "${WORKSPACE_PATH}/.idea" ]
  then
    if [ -z "${mode}" ]
    then
      mode="-u"
    elif [ "${mode}" != "-u" ]
    then
      doFail "Workspace ${WORKSPACE} is not initialized.\nReverse merge is not possible."
    fi
  fi
  if [ -n "${mode}" ]
  then
    doConfigureWorkspace "${SETTINGS_PATH}/intellij/workspace" "${WORKSPACE_PATH}" ${mode}
  fi
}

function doStartIntellij() {
  doConfigureIntellij "-u"
  echo "launching IntelliJ..."
  local IDEA="${IDEA_HOME}/bin/idea64.exe"
  if [ ! -f "${IDEA}" ];
  then
	IDEA="${IDEA_HOME}/bin/idea"
  fi
  if [ ! -f "${IDEA}" ];
  then
    IDEA="${IDEA_HOME}/idea"
  fi
  if doIsMacOs
  then
	echo "MacOs command ${IDEA}"
    open "${IDEA}" --args "${@}"
  else
    echo "command ${IDEA}"
    "${IDEA}" "${@}" &
  fi
}

# CLI
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  echo "Manage IntelliJ IDE and workspace."
  echo
  echo "Arguments:"
  echo " --all              if provided as first arg then to command will be invoked for each workspace"
  echo " setup              setup IntelliJ (install or update)"
  echo " run | start        launch IntelliJ IDE (default if no argument is given)"
  echo " ws-up[date]        update IntelliJ workspace"
  echo " ws-re[verse]       reverse merge changes from workspace into settings"
  echo " ws-reverse-add     reverse merge adding new properties"
  echo " create-script      create intellij-${WORKSPACE} script if not already exists"
  exit
fi
IDEA_HOME="${DEVON_IDE_HOME}/software/intellij"
if [ -z "${1}" ]
then
  doSetup
  doStartIntellij
fi
if [ "${1}" = "--all" ]
then
  shift
  doDevonCommandAllWorkspaces intellij "${@}"
fi
while [ -n "${1}" ]
do
  if [ "${1}" = "run" ] || [ "${1}" = "start" ]
  then
    shift
    doStartIntellij "${@}"
  elif [ "${1}" = "ws-up" ] || [ "${1}" = "ws-update" ]
  then
    doConfigureIntellij "-u"
  elif [ "${1}" = "ws-re" ] || [ "${1}" = "ws-reverse" ]
  then
    doConfigureIntellij "-i"
  elif [ "${1}" = "ws-reverse-add" ]
  then
    doConfigureIntellij "-x"
  elif [ "${1}" = "setup" ]
  then
    doSetup setup
    doCreateIdeScript intellij
  elif [ "${1}" = "create-script" ]
  then
    doCreateIdeScript intellij
  else
    doFail "Unknown argument: ${1}"
  fi
  shift
done
