#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup create help"
  fi
  exit
fi

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions
TOOL_VERSION_COMMAND="ionic -v"
# shellcheck source=scripts/commandlet-cli
source "$(dirname "${0}")"/../commandlet-cli

# $1: optional setup
function doSetup() {
  if command -v ionic &> /dev/null
  then
    if [ "${1}" != "silent" ]
    then
      doEcho "ionic-cli (ionic) is already installed at $(command -v ionic)"
    fi
  else
    doDevonCommand npm setup silent
    doDevonCommand npm install -g @ionic/cli@latest --unsafe
  fi
}

#CLI
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  echo "Setup or run ionic-cli (ionic)."
  echo
  echo "Arguments:"
  echo "setup                 setup ionic-cli (install and verify)"
  echo "create                create a new devon4ng ionic project"
  echo "«args»                call ionic with the specified arguments"
  exit
fi

if [ -z "${1}" ] || [ "${1}" = "setup" ]
then
  doSetup "${2}"
elif [ "${1}" = "create" ]
then
  shift
  doSetup silent
  ionic start "${@}"
else
  doSetup silent
  ionic "${@}"
fi
