#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version help"
  fi
  exit
fi

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions
JMC_HOME="${DEVON_IDE_HOME}/software/jmc"
# shellcheck source=scripts/commandlet-cli
source "$(dirname "${0}")"/../commandlet-cli

# Call jmc with specified arguments.
function doRun() {
  if [ -z "$(ls -A "${JMC_HOME}")" ]
  then
    doSetup silent
  fi
  doRunCommand "${JMC_HOME}/jmc ${*} &"
}

# JDK Mission Control installation
function doSetup() {
  local install_dir="${DEVON_IDE_HOME}/updates/install/jmc"
  doInstall "jmc" "${JMC_VERSION}" "${1}" "" "${install_dir}"
  doRunCommand "mkdir -p ${JMC_HOME}"
  doRunCommand "mv -f '${install_dir}/JDK Mission Control/' ${JMC_HOME}"
  doRunCommand "mv -f '${install_dir}/legal/' ${JMC_HOME}"
  doRunCommand "mv -f '${install_dir}/.devon.software.version' ${JMC_HOME}"
  rm -rf "${install_dir}"
  return 0
}

# CLI
case ${1} in
"help" | "-h")
  echo "Setup or run Java Mission Control."
  echo
  echo "Arguments:"
  echo " setup                          install Openshift CLI on your machine."
  echo " «args»                         call jmc with the specified arguments."
;;
"setup" | "s")
  doSetup "${2}"
;;
*)
  doRun "${@}"
;;
esac
