#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version help"
  fi
  exit
fi

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions
KOTLIN_HOME="${DEVON_IDE_HOME}/software/kotlin"
TOOL_VERSION_COMMAND="kotlin version"
# shellcheck source=scripts/commandlet-cli
source "$(dirname "${0}")"/../commandlet-cli

# $1: optional silent mode
function doSetup() {
  export KOTLIN_HOME="${DEVON_IDE_HOME}/software/kotlin"
  doInstall "kotlin" "1.8.10" "${1}"
  return 0
}

# CLI
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  echo "Install Kotlin."
  echo
  echo "Arguments:"
  echo " setup          setup Kotlin (install and verify)"
elif [ -z "${1}" ] || [ "${1}" = "setup" ]
then
  doSetup "${2}"
else
  doFail "Unknown argument ${1}"
fi
