#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version help"
  fi
  exit
fi

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions
KOTLINC_HOME="${DEVON_IDE_HOME}/software/kotlinc"
TOOL_VERSION_COMMAND="kotlinc -version"
# shellcheck source=scripts/commandlet-cli
source "$(dirname "${0}")"/../commandlet-cli

# Call kotlin with specified arguments.
function doRun() {
  doSetup silent
  doRunCommand "${KOTLINC_HOME}/kotlinc ${*}"
}

# $1: optional silent mode
function doSetup() {
  doInstall "kotlinc" "${KOTLINC_VERSION}" "${1}"
  return 0
}

# CLI
case ${1} in
"help" | "-h")
  echo "Install kotlinc."
  echo
  echo "Arguments:"
  echo " setup                          install kotlinc on your machine."
  echo " «args»                         call kotlin with the specified arguments. Call kotlinc --help for details or use kotlinc directly as preferred."
;;
"setup" | "s" | "")
  doSetup "${2}"
;;
*)
  doRun "${@}"
;;
esac
