#!/usr/bin/env bash

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions
for migration in "$(dirname $0)/../migrations"/*
do
  from_version="${1}"
  to_version="${migration/*\//}"
  doVersionCompare "${from_version}" "${to_version}"
  result="${?}"
  if [ "${result}" -eq 0 -o "${result}" -eq 2 ]
  then
    "${migration}"
  fi	
done