#!/usr/bin/env bash
source "$(dirname "${0}")"/../functions

# $1: optional setup
function doSetup() {
  if [ -n "${1}" ] || [ ! -d "${MAVEN_HOME}" ]
  then
    local software_version=${MAVEN_VERSION:-3.6.0}
    local download_url=http://ftp.fau.de/apache/maven/maven-3/${software_version}/binaries/apache-maven-${software_version}-bin.tar.gz
    doInstall "${MAVEN_HOME}" "${download_url}" "maven" "${software_version}" 'apache-maven-*' "" "all"
  fi
  if [ -n "${1}" ]
  then
    if [ -d "${SETTINGS_PATH}" ]
    then
      M2_DIR="${DEVON_IDE_HOME}/conf/.m2"
      if [ ! -e "${M2_DIR}" ]
      then
        mkdir -p "${M2_DIR}"
      fi
      if [ ! -e "${M2_DIR}/settings-security.xml" ]
      then
        MASTER_PASSWORD="$(head -c 20 /dev/random | base64)"
        MASTER_PASSWORD="$(mvn --encrypt-master-password ${MASTER_PASSWORD})"
        echo -e "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<settingsSecurity>\n  <master>${MASTER_PASSWORD}</master>\n</settingsSecurity>" > ${M2_DIR}/settings-security.xml
        echo "Successfully created ${M2_DIR}/settings-security.xml"
        MASTER_PASSWORD=
      fi
    else
      echo "WARNING: Settings are missing at ${SETTINGS_PATH}"
      echo "Please run the following command to fix:"
      echo "devon setup"
    fi
    doRunCommand "mvn -v" "verify installation of maven"
  fi
}

# $@: optional maven arguments
function doGetProjectVersion() {
  doSetup
  local maven_project_version
  local version_list="$(mvn -q exec:exec -Dexec.executable=echo -Dexec.args='${project.version}' ${@})"
  if [ "${?}" = 0 ]
  then
    maven_project_version="$(echo "${version_list}" | grep -v '^dev\(-SNAPSHOT\)*$' | sort -u )"
    if [ -z "${maven_project_version}" ]
    then
      maven_project_version="$(echo "${version_list}" | sort -u )"
    fi
    if [[ "${maven_project_version}" == *$'\n'* ]]
    then
      doFail "Multiple versions in reactor:\n${maven_project_version}"
    fi
  else
    doFail "${version_list}\nYour maven project has errors. Please run 'mvn install' and retry."
  fi
  echo ${maven_project_version}
}

# $1: new version
# $2: current version
# $3: optional backup flag (cleanBackup, keepBackup, cleanKeepBackup)
function doSetProjectVersion() {
  local current_version="${2}"
  if [ -z "${2}" ]
  then
    current_version="$(doGetProjectVersion)"
  fi
  if [ "${current_version}" = "${1}" ]
  then
    echo "Maven version is already set to ${1}. Nothing to change."
    return
  fi
  if [ -e ".mvn/maven.config" ]
  then
    # https://maven.apache.org/maven-ci-friendly.html
    local maven_config="$(cat .mvn/maven.config)"
    local current_revision="${2/-SNAPSHOT/}"
    if [ "${maven_config/${current_revision}/}" = "${maven_config}" ]
    then
      doConfirmWarning "Your .mvn/maven.config does not contain the expected revision ${current_revision}:\n${maven_config}"
    fi
    local revision="${1/-SNAPSHOT/}"
    local changelist=""
    local mvn_version_arg=""
    if [ "${revision}" = "${1}" ]
    then
      mvn_version_arg="-Dchangelist="
    else
      changelist="-SNAPSHOT"
    fi
    local updated_config="$(echo "${maven_config}" | sed "s/-Drevision=[^ ]*/-Drevision=${revision}/" | sed "s/-Dchangelist=[^ ]*/-Dchangelist=${changelist}/")"
    if [ "${updated_config}" != "${maven_config}" ]
    then
      echo "${updated_config}" > .mvn/maven.config
      doEcho "updated .mvn/maven.config\nfrom: ${maven_config}\nto: ${updated_config}"
      return
    fi
  fi
  local module_list="$(mvn -q exec:exec -Dexec.executable=pwd)"
  if [ "${?}" = 0 ]
  then
    local cwd="${PWD}"
    for folder in ${module_list}
    do
      cd "${folder}"
      doSetPomVersion ${@}
    done
    cd "${cwd}"
  else
    doFail "${module_list}"
  fi
}

# $1: new version
# $2: current version
# $3: optional backup flag (cleanBackup, keepBackup, cleanKeepBackup)
function doSetPomVersion() {
  if [ -f pom.xml.bak ]
  then
    if [ "${3}" = "cleanBackup" ] || [ "${3}" = "cleanKeepBackup" ]
    then
      doEcho "Cleaning previous backup ${PWD}/pom.xml.bak"
      rm pom.xml.bak
    fi
  fi
  doSetup
  local maven_project_version="$(mvn -q exec:exec -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive)"
  if [ "${maven_project_version}" = "${1}" ] 
  then
    echo "No changes needed for ${PWD}/pom.xml"
    return
  fi
  if [ ! -f pom.xml.bak ]
  then
    doEcho "Creating backup of ${PWD}/pom.xml"
    cp pom.xml pom.xml.bak
  fi
  local pom_elements="$(cat pom.xml.bak | grep ${2})"
  if [ "${?}" != 0 ]
  then
    doFail "Version ${2} not found in POM ${PWD}/pom.xml"
    exit 255
  fi
  if [[ "${pom_elements}" == *$'\n'* ]]
  then
    doConfirmWarning "Multiple matches of version in your pom.xml:\n${pom_elements}"
  fi
  cat pom.xml.bak | sed "s/${2}/${1}/g" > pom.xml
  if [ "${3}" != "keepBackup" ] && [ "${3}" != "cleanKeepBackup" ]
  then
    doEcho "Cleaning backup ${PWD}/pom.xml.bak"
    rm pom.xml.bak
  fi
}

# $1: quiet option (-q, --quiet, quiet) or anything else to echo
function doCheckTopLevelProject() {
  if [ ! -f pom.xml ]
  then
    doEcho "${1}" "Not in a maven project: ${PWD}"
    exit 255
  fi
  local relative_path
  if grep -q "<parent>" pom.xml
  then
    relative_path="$(grep -q "<relativePath" pom.xml)"
    if [ "${?}" = 0 ]
    then
      if [[ "${relative_path}" == *"<relativePath/>"* ]]
      then
        relative_path=""
      else
        relative_path="$(echo $relativePath | sed 's/.*\<relativePath>\(.*\)\<\/relativePath>/\1/')"
      fi
    else
      relative_path="../pom.xml"
    fi
  fi
  if [ -n "${relative_path}" ]
  then
    if [ -f "${relative_path}" ]
    then
      doEcho "${1}" "Parent with existing relativePath ${relative_path}"
      doEcho "${1}" "You are inside a maven module."
      exit 254
    else
      doEcho "${1}" "Parent with non-existing relativePath ${relative_path}"
    fi
  fi
  doEcho "${1}" "You are inside a top-level maven project"
}

function doRunBuild() {
  local maven_cmd="mvn"
  if [ -x mvnw ]
  then
    maven_cmd="./mvnw"
  else
    doSetup
  fi
  doEcho "Running: ${maven_cmd} ${@}"
  if doIsQuiet
  then
    ${maven_cmd} -q ${@}
  else
    ${maven_cmd} ${@}
  fi
}

# CLI
MAVEN_HOME="${DEVON_IDE_HOME}/software/maven"
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  echo "Setup or run maven build tool."
  echo
  echo "Arguments:"
  echo "                          run default build"
  echo " setup                    setup maven (install, verify, configure)"
  echo " get-version              get the current project version"
  echo " set-version «nv» [«cv»]  set the current project version to new version «nv» (assuming current version is «cv»)"
  echo " check-top-level-project  check if we are running on a top-level project or fail if in a module or no maven project at all"
  echo " release                  start a clean deploy release build"
  echo " «args»                   call maven with the specified arguments"
  echo
  echo "Options:"
elif [ -z "${1}" ]
then
  doRunBuild ${MVN_BUILD_OPTS:-clean install}
elif [ "${1}" = "setup" ]
then
  doSetup setup
elif [ "${1}" = "get-version" ]
then
  doGetProjectVersion
elif [ "${1}" = "set-version" ] && [ -n "${2}" ]
then
  shift
  doSetProjectVersion ${@}
elif [ "${1}" = "check-top-level-project" ]
then
  shift
  doCheckTopLevelProject ${@}
elif [ "${1}" = "release" ]
then
  export GPG_TTY=$(tty)
  doRunBuild ${MVN_RELEASE_OPTS:-clean deploy -Dchangelist= -Pdeploy}
else
  doRunBuild ${@}
fi
