#!/bin/bash
cd `dirname $0`
cd ../..
source scripts/functions

#CLI
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  echo "Setup or run angular-cli (ng)."
  echo
  echo "Arguments:"
  echo "setup      setup angular-cli (install and verify)"
  echo "«args»     call maven with the specified arguments"
  exit
fi

if [ -z "${1}" ] || [ "${1}" = "setup" ]
then
  setup=true
fi

if which ng &> /dev/null
then
  if [ "${setup}" = "true" ]
  then
    echo "angluar-cli (ng) is already installed at `which ng`"
  fi
else
  doRunCommand "npm install -g @angular/cli@latest --unsafe" "install angular-cli"
fi

if [ "${setup}" != "true" ]
then
  ng "${@}"
fi
