#!/usr/bin/env bash
source "$(dirname "${0}")"/../functions

#CLI
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  echo "Setup or run angular-cli (ng)."
  echo
  echo "Arguments:"
  echo "setup                 setup angular-cli (install and verify)"
  echo "«args»                call maven with the specified arguments"
  echo
  echo "Options:"
  exit
fi

if [ -z "${1}" ] || [ "${1}" = "setup" ]
then
  setup=true
fi

if command -v ng &> /dev/null
then
  if [ "${setup}" = "true" ]
  then
    echo "angluar-cli (ng) is already installed at $(command -v ng)"
  fi
else
  doRunCommand "npm install -g @angular/cli@latest --unsafe" "install angular-cli"
fi

if [ "${setup}" != "true" ]
then
  ng ${@}
fi