#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version help"
  fi
  exit
fi

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions
OC_HOME="${DEVON_IDE_HOME}/software/oc"
TOOL_VERSION_COMMAND="-"
# shellcheck source=scripts/commandlet-cli
source "$(dirname "${0}")"/../commandlet-cli

# Call oc with specified arguments.
function doRun() {
  doSetup silent
  doRunCommand "${OC_HOME}/oc ${*}"
}

# openshift installation
function doSetup() {
  doInstall "oc" "${OC_VERSION}" "${1}"
  return 0
}

# CLI
case ${1} in 
"help" | "-h")
  echo "Setup or run Openshift CLI."
  echo
  echo "Arguments:"
  echo " setup                          install Openshift CLI on your machine."
  echo " «args»                         call oc with the specified arguments. Call oc --help for details or use oc directly as preferred."
;;
"setup" | "s")
  doSetup "${2}"
;;
*)
  doRun "${@}"
;;
esac
