#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version help"
  fi
  exit
fi

if [ -n "${DEVON_IDE_TRACE}" ]; then set -vx; fi
OPENSHIFT_HOME="${DEVON_IDE_HOME}/software/oc"
TOOL_VERSION_COMMAND="oc version"
# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions


# Call oc with specified arguments.
function doRun() {
  doSetup silent
  doRunCommand "${OPENSHIFT_HOME}/oc ${*}"
}

# openshift installation
function doSetup() {
  if [ ! -d "${OPENSHIFT_HOME}" ] || [ "${1}" != "silent" ]
  then
    # Getting latest release
    if [ -z "${OC_VERSION}" ]
    then
      doEcho "Getting latest release..."
      OC_VERSION=$(curl "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/" | awk -F "openshift-client-windows-" '/openshift-client-windows-/ {print $2}' | head -1 | awk -F'.zip' '{print $1}')
    fi
    doInstall "oc" "${OC_VERSION}"
  fi

  if [ "${1}" != "silent" ] && ! doIsQuiet
  then
    doRunCommand "${TOOL_VERSION_COMMAND}"
  fi 
}

# CLI
case ${1} in 
"help" | "-h")
  echo "Setup or run Openshift CLI."
  echo
  echo "Arguments:"
  echo " setup                          install Openshift CLI on your machine."
  echo " «args»                         call oc with the specified arguments. Call oc --help for details or use oc directly as preferred."
;;
"setup" | "s")
  doSetup "${2}"
;;
*)
  doRun "${@}"
;;
esac
