#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version help"
  fi
  exit
fi

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions
QUARKUS_HOME="${DEVON_IDE_HOME}/software/quarkus"
TOOL_VERSION_COMMAND="quarkus -v"
# shellcheck source=scripts/commandlet-cli
source "$(dirname "${0}")"/../commandlet-cli

# Call quarkus with specified arguments.
function doRun() {
  doSetup silent
  doRunCommand "${QUARKUS_HOME}/bin/quarkus ${*}"
}

# quarkus CLI installation
function doSetup() {
  doInstall "quarkus" "${QUARKUS_VERSION}" "${1}"
  return 0
}

# CLI
case ${1} in 
"help" | "-h")
  echo "Setup or run QUARKUS CLI."
  echo
  echo "Arguments:"
  echo " setup                    install QUARKUS CLI on your machine."
  echo " <<args>>                 call quarkus with the specified arguments. Call quarkus --help for details or use quarkus directly as preferred."
  echo
;;
"setup" | "s")
  doSetup "${2}"
;;
*)
  doRun "${@}"
;;
esac
