#!/bin/bash
cd `dirname $0`
cd ../..
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  echo "Shortcut for 'devon ide setup'."
  exit
elif [ -n "${1}" ]
then
  doFail "Undefined option ${1}"
  exit 255
fi
${DEVON_IDE_HOME}/scripts/command/ide setup
