#!/usr/bin/env bash

# autocompletion list
if [ "${1}" = "shortlist" ]
then
  if [ -z "${2}" ]
  then
    echo "setup version start stop analyze help"
  fi
  exit
fi

# shellcheck source=scripts/functions
source "$(dirname "${0}")"/../functions
SONAR_HOME="${DEVON_IDE_HOME}/software/sonar"
TOOL_VERSION_COMMAND="ls '${SONAR_HOME}/lib/sonar-application'-*.jar | sed 's/.*sonar-application-//' | sed 's/\.jar//'"
# shellcheck source=scripts/commandlet-cli
source "$(dirname "${0}")"/../commandlet-cli

# $1: optional setup
function doSetup() {
  doDevonCommand java setup silent
  doInstall "sonar" "${SONAR_VERSION}" "${1}" "" "${SONAR_HOME}" "-"
  return 0
}

function doStart() {
  doSonar start
}

function doStop() {
  doSonar stop
}

function doSonar() {
  doSetup silent
  if doIsWindows
  then
    if [ "${1}" = "start" ]
    then
      #"${SONAR_HOME}/bin/windows-x86-64/SonarService.bat"
      "${SONAR_HOME}/bin/windows-x86-64/StartSonar.bat"
    elif [ "${1}" = "stop" ]
    then
      "${SONAR_HOME}/bin/windows-x86-64/SonarService.bat" stop
    else
      doFail "Unknown sonar command: ${1}"
    fi
  elif doIsMacOs
  then
    "${SONAR_HOME}/bin/macosx-universal-64/sonar.sh" "${1}"
  else
    "${SONAR_HOME}/bin/linux-x86-64/sonar.sh" "${1}"
  fi
  if [ "${1}" = "start" ]
  then
    echo "SonarQube is running at localhost on the following port (default 9000):"
    grep "sonar.web.port" "${SONAR_HOME}/conf/sonar.properties"
  fi
}

function doAnalyze() {
  doDevonCommand mvn sonar:sonar
}

# CLI
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  echo "Setup or run SonarQube server on local machine."
  echo
  echo "Arguments:"
  echo " start                          start local SonarQube server"
  echo " stop                           stop local SonarQube server"
  echo " setup                          setup SonarQube (install, verify, configure)"
  echo " analyze                        analyze current project with SonarQube"
elif [ "${1}" = "setup" ]
then
  doSetup "${2}"
elif [ "${1}" = "start" ]
then
  doStart
elif [ "${1}" = "stop" ]
then
  doStop
elif [ "${1}" = "analyze" ]
then
  shift
  doAnalyze "${@}"
else
  doFail "undefined argument ${*}"
fi
