#!/bin/bash
cd `dirname $0`
cd ../..
source scripts/functions
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  echo "Update devon-ide scripts."
  echo
  echo "Arguments:"
  echo "                          by default update scripts package to the latest version"
  echo "«package»                 update specified package to latest version"
  echo "«package» to «version»    update (or downgrade) specified package to specified version"
  exit
fi

target="${DEVON_IDE_HOME}"
url="https://repo.maven.apache.org/maven2/com/devonfw/tools/ide/"
package="devon-ide-scripts"
target_version="LATEST"
current_version=
if [ -n "${1}" ]
then
  package="devon-ide-${1}"
  if [ "${2}" = "to" ]
  then
    if [ -z "${3}" ]
    then
      echo "Missing version argument!"
      echo "devon update to «version»"
      exit -1
    fi
    version="${3}"
  elif [ -n "${2}" ]
  then
    doFail "Undefined argument ${2}!"
  fi
fi
if [ "${package}" = "devon-ide-scripts" ]
then
  current_version="${devon_ide_version}"
  if [ "${OSTYPE:0:6}" = "darwin" ]
  then
    suffix="mac.tar.gz"
  else
    suffix="linux.tar.gz"
  fi
else
  if [ "${package}" = "devon-ide-settings" ]
  then
    if [ -d "${SETTINGS_PATH}/.git" ]
    then
      cd ${SETTINGS_PATH}
      git pull
      result=${?}
      if [ "${result}" = 0 ]
      then
        echo "Updated your settings successfully via git pull."
        exit
      else
        doFail "Failed to update your settings via git pull." ${result}
      fi
    elif [ -n "${SETTINGS_URL}" ]
    then
      doInstall "${SETTINGS_PATH}" "${SETTINGS_URL}"
      exit
    fi
    target="${SETTINGS_PATH}"
  fi
  suffix=".zip"
fi

doUpgradeMavenArtifact "${target}" "https://github.com/devonfw/devon-ide/wiki/devon-ide-scripts" "${package}" "${target_version}" "${suffix}" "${current_version}"
