#!/bin/bash
cd `dirname $0`
cd ../..
if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
then
  echo "Launch Visual Studio Code and/or manage VSCode workspace."
  echo
  echo "Arguments:"
  echo " run | start        launch VSCode IDE (default if no argument is given)"
  echo " ws-up[date]        update VSCode workspace"
  echo " ws-re[verse]       reverse merge changes from workspace into settings"
  echo " ws-reverse-add     reverse merge adding new properties"
  echo " create-script      create vscode-${WORKSPACE} script if not already exists"
  exit
fi
RUN=
while [ -n "${1}" ]
do
  RUN=
  if [ "${1}" = "run" ] || [ "${1}" = "start" ]
  then
    RUN=true
  else
    if [ "${RUN}" != "true" ]
    then
      RUN=false
    fi
    
    if [ "${1}" = "ws-up" ] || [ "${1}" = "ws-update" ]
    then
      CONFIGURATOR_MODE="-u"
      CONFIGURATOR_ACTION="updated"
    elif [ "${1}" = "ws-re" ] || [ "${1}" = "ws-reverse" ]
    then
      CONFIGURATOR_MODE="-i"
      CONFIGURATOR_ACTION="merged back to settings"
    elif [ "${1}" = "ws-reverse-add" ]
    then
      CONFIGURATOR_MODE="-x"
      CONFIGURATOR_ACTION="merged back to settings (including new properties)"
    elif [ "${1}" = "create-script" ]
    then
      CREATE_SCRIPT=true
    else
      echo "Undefined argument: ${1}"
      exit -1
    fi
  fi
  shift
done

if [ ! -d "${WORKSPACE_PATH}" ]; then
    echo "Could not find folder '${WORKSPACE_PATH}' (from variable WORKSPACE_PATH)"
    echo "Execution aborted"
    exit 1
fi
TEMPLATES_PATH=${SETTINGS_PATH}/vscode/workspace
if [ ! -d "${TEMPLATES_PATH}" ]
then
    echo "Could not find folder '${TEMPLATES_PATH}' (from variable TEMPLATES_PATH)"
    echo "Execution aborted"
    exit 1
fi
REPLACEMENT_PATTERNS_PATH=${TEMPLATES_PATH}/replacement-patterns.properties
if [ ! -e "${REPLACEMENT_PATTERNS_PATH}" ]
then
  touch "${REPLACEMENT_PATTERNS_PATH}"
fi

if [ ! -d "${WORKSPACE_PATH}/.vscode" ]
then
  if [ "${CONFIGURATOR_MODE}" = "-i" ] || [ "${CONFIGURATOR_MODE}" = "-x" ]
  then
    echo "ERROR: Workspace ${WORKSPACE} is not initialized."
    echo "Reverse merge is not possible."
    exit -1
  fi
  CONFIGURATOR_MODE="-u"
  CONFIGURATOR_ACTION="created"
fi 

if [ -n "${CONFIGURATOR_MODE}" ]
then
  java -jar ${DEVON_IDE_HOME}/scripts/lib/${IDE_CONFIGURATOR} -cp ${DEVON_IDE_HOME}/scripts/lib/*.jar -t "${TEMPLATES_PATH}" -w "${WORKSPACE_PATH}" -v "${REPLACEMENT_PATTERNS_PATH}" ${CONFIGURATOR_MODE}
  echo "VSCode preferences for workspace ${WORKSPACE} have been ${CONFIGURATOR_ACTION}"
fi

if [ "${CREATE_SCRIPT}" = "true" ]
then
 echo "#!/bin/bash" > vscode-$WORKSPACE
 echo "cd \`dirname \${0}\`" >> vscode-$WORKSPACE
 echo "cd workspaces/${WORKSPACE}" >> vscode-$WORKSPACE
 echo "source ${DEVON_IDE_HOME}/scripts/devon vscode" >> eclipse-$WORKSPACE
 chmod a+x vscode-$WORKSPACE
 echo "Created script vscode-$WORKSPACE"
fi

if [ "${RUN}" != "false" ]
then
  echo "launching VSCode..."
  code "${WORKSPACE_PATH}"
fi