name: Delete cancelled workflow runs
on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete cancelled workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: cancelled
