name: Label-PR
on:
  pull_request_target: # *_target workaround for https://github.com/actions/labeler/issues/12
    types: [opened, reopened, synchronize, unlocked, unlabeled]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Label by changed paths
      uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: false
        configuration-path: .github/labeler.yml