name: GraalVM Native Image builds
on: push
jobs:
  build:
    name: Build native images
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: feature/natives-release
          
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          
      - name: Build native images with maven plugin
        run: |
          ls /home/runner/work/ide/ide/ide/src/main
      - uses: actions/upload-artifact@v3
        with:
          name: Upload native images
          path: ide/target/*.tar.gz

  test:
    name: Re-use Cache
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
    - name: Display structure of downloaded files
      run: ls -R
