name: GraalVM Native Image builds
on: push
jobs:
  build-natives:
    name: Build native images
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: feature/release-native-images
          
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          
      - name: Build native images with maven plugin
        shell: bash
        run: |
          cd ide
          mvn -B -X -Pnative -DskipTests=true package
          cd package/target
          tar -cvf ide-${{ runner.os }}.tar devon*
          ls -lR

      - uses: actions/upload-artifact@v3
        with:
          name: natives
          path: ide/package/target/ide*.tar

  attach-artifacts:
    name: Attach native images and create release
    runs-on: ubuntu-latest
    needs: [build-natives]
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: actions/download-artifact@v3
      - name: Create tar.gz archives for release
        run: |
          cd scripts
          mvn -B -ntp -DskipTests=true -Dstyle.color=always install
          cd ..
          mv ./natives/ide-Windows.tar ./ide/package/natives/
          tar -rvf ./ide/package/natives/ide-Windows.tar ./scripts/target/package/system ./scripts/target/package/devonfw-ide-doc.pdf
          gzip ./ide/package/natives/ide-Windows.tar
          mv ./natives/ide-MacOS.tar ./ide/package/natives/
          tar -rvf ./ide/package/natives/ide-MacOS.tar ./scripts/target/package/system ./scripts/target/package/devonfw-ide-doc.pdf
          gzip ./ide/package/natives/ide-MacOS.tar
          mv ./natives/ide-Linux.tar ./ide/package/natives/
          tar -rvf ./ide/package/natives/ide-Linux.tar ./scripts/target/package/system ./scripts/target/package/devonfw-ide-doc.pdf
          gzip ./ide/package/natives/ide-Linux.tar
          ls -R
          gh release create v1.0.1 ./ide/package/natives/*.tar.gz
         
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
