name: GraalVM Native Image builds
on: push
jobs:
  build:
    name: Build native images
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          
      - name: Build native images with maven plugin
        run: |
          mvn -B -X -Pnative -DskipTests=true package
          ls -l
          cd target
