name: GraalVM Native Image builds
on: push
jobs:
  build-natives:
    name: Build native images
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: feature/natives-release
          
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          
      - name: Build native images with maven plugin
        run: mvn -B -X -Pnative -DskipTests=true package

      - uses: actions/upload-artifact@v3
        with:
          name: executables
          path: ide/target/ide-cli*.tar.gz

  attach-artifacts:
    name: Attach native images to build for deploy
    runs-on: ubuntu-latest
    needs: [build-natives]
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: |
          mvn -B -ntp -DskipTests=true -Dstyle.color=always install
          gh release create v1.0.0 ./executables/*.tgz
          ls -R
