name: GraalVM Native Image builds
on: push
jobs:
  build-natives:
    name: Build native images
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: feature/release-native-images
          
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          
      - name: Build native images with maven plugin
        shell: bash
        run: |
          cd ide
          mvn -B -X -Pnative -DskipTests=true package
          cd package/target
          file=devon*
          mv -- "$file" "${file//devon/devon-${{ runner.os}}"
          ls -lR

      - uses: actions/upload-artifact@v3
        with:
          name: natives
          path: ide/package/target/devon*

  attach-artifacts:
    name: Attach native images and create release
    runs-on: ubuntu-latest
    needs: [build-natives]
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: |
          tar -czvf ./ide/package/natives/ide-windows.tar.gz ./natives/devon.exe ./scripts/target/package/system ./scripts/target/package/devonfw-ide-doc.pdf
          mvn -B -ntp -DskipTests=true -Dstyle.color=always install
          ls -R
          gh release create v1.0.1 ./ide/package/natives/*.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
