name: GraalVM Native Image builds
on: push
jobs:
  build:
    name: Build native images
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: 'feature/natives-release'
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          
      - name: Build native images with maven plugin
        run: |
          cd ide
          echo ${{ runner.os }} >> test-${{ runner.os }}.txt
          ls
      - uses: actions/cache@v2
        id: cache-executables
        with:
          path: ./*
          key: ${{ secrets.GITHUB_TOKEN }}

  cache-use-build:
    name: Re-use Cache
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/cache@v2
        id: cache-executables
        with:
          path: ./*
          key: ${{ secrets.GITHUB_TOKEN }}
      - run: ls
