name: Quick Test Ubuntu
on: push
jobs:
  test:
    name: Integration test Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build project with Maven
        run: |
          export INTEGRATION_TEST=true
          mvn -B -ntp install
