name: Integration Test Windows Light
on: push
jobs:
  test:
    name: Integration test Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Set up shellcheck
        run: choco install shellcheck
      - name: Build project with Maven
        run: |
          export INTEGRATION_TEST=true
          mvn -B -ntp install