name: test
on: push

jobs:
  updateURLS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ide
        uses: actions/checkout@v3
      - name: Checkout ide-urls
        uses: actions/checkout@v3
        with:
          repository: alfeilex/ide-urls
          path: ide-urls
          token: ${{ secrets.ACTION_PUSH_TOKEN }}
      - name: Build and run url updater
        run: touch testingFile.txt
      - name: Commit and push to ide-urls
        run: |
          cd ide-urls
          git checkout -b with-checksum-testing
          git add .
          git config --global user.name ${{ secrets.BUILD_USER }}
          git config --global user.email ${{ secrets.BUILD_USER_EMAIL }}
          git commit -m "Update urls"
          git push
