name: Integration Test MacOS
on: 
  workflow_dispatch
jobs:
  test:
    name: Integration test MacOS
    runs-on: macos-latest
    needs: verify_commit
    if: ${{ needs.verify_commit.outputs.RUN_BUILD == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Set up shellcheck
        run: brew install shellcheck
      - name: Build project with Maven
        run: |
          export INTEGRATION_TEST=true
          mvn -B -ntp install
